### ISSUE TITLE
Mint Login Broken Since Mint Refresh

### ISSUE THREAD

**Issue by ovitch** [jprouty/mint-amazon-tagger#100]
I am using the latest release. I usually fetch the report but in my last attempt re-used the one already downloaded by the app.

Issue: 
- I enter my credentials for login but the tagger get stuck on login to mint and eventually times out with the error - cannot log into mint
- Despite the error, I am fully logged in when this happens. 

Any suggestion? I tried to do the "I will login myself". I checked I have the latest Chrome update. Looking for ideas!

**Comment by jprouty** [comment]
Hi @ovitch! You're not crazy; it seems that Mint has changed the login flow. I've made some initial improves and published it as version 1.44. Give that a shot and see if it gets you going again. Any input is helpful, thanks!

**Comment by ovitch** [comment]
@jprouty thank you for your comment. Still gets stuck. I wonder if this would work in a private window. 
When login in I get the intuit account selector (the intuit SSO). Then password (with option 2FA), then loading in the platform. 

It seems they made several improvement on the platform too so maybe there is more to it.

Did you succeed to run in on your end?

**Comment by ovitch** [comment]
@jprouty Here is my testing so far
- logging manually: idle in logging to mint even after I complete the process
- logging automatically: have to interact with Chrome to click on the profile.

Either one end up in the same loop. The script doesn't realize I am logged in and cannot move to the next step.

Additionally, it seems the refund file structure from Amazon is different from the past (see other issue raised)

**Comment by mmratio** [comment]
I'm having a similar issue, though there may be more going on.
Here's the output from the ChromeDriver:


DevTools listening on ws://127.0.0.1:16567/devtools/browser/91027118-c68b-4878-ba7e-f6fe26b54782
[728:22416:0604/195417.975:ERROR:device_event_log_impl.cc(214)] [19:54:17.975] USB: usb_service_win.cc:104 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
[728:2784:0604/195512.648:ERROR:util.cc(127)] Can't create base directory: C:\Program Files\Google\GoogleUpdater

**Comment by codam** [comment]
Hi @jprouty 
Great looking tool!
I'm having the same issue with v1.44 FYI

**Comment by jprouty** [comment]
Thanks for all of the details / reports! The new Mint version requires a moderate rewrite on the mint client for the tagger. I'll get to this within the next 48 hrs.

**Comment by jprouty** [comment]
Yes, please retry with release 1.45 and report back here. Thanks for your patience.

**Comment by burkematthew** [comment]
@jprouty just wanted to give a heads up that we've done a good amount of rewrite for Mint's new UI over at https://github.com/mintapi/mintapi.  It seems to be a constant battle as little tweaks have been necessary just about every week.  Feel free to use whatever if it's at all helpful!

**Comment by jprouty** [comment]
Thanks for the heads up @burkematthew. I split ways with mintapi back when it was still v1, due to unwanted dependencies and a slow release cadence that didn't always result in fast enough update to unbreak this tool. However, it looks like v2 is a big improvement, with more active contributors. I will take another consideration if this continues to be an issue.

@ovitch, Please reopen if you are still having login issue. The flow is working for me and I have included a few tweaks as of release 1.53. Cheers.
