### ISSUE TITLE
Mint Amazon Tagger 1.44 no longer recognized manually logged in Mint

### ISSUE THREAD

**Issue by felciano** [jprouty/mint-amazon-tagger#103]
I am using v1.44 GUI with manually downloaded Amazon transaction files and a manual log in to Mint itself. I am able to log in successfully by hand to the Chrome window that `mint-amazon-tagger` brings up. However, the `mint-amazon-tagger` GUI continues to display a "Tagger is running..." window displaying "Logging in to mint.com" with a pgoress bar.

I'm on the new UI version of Mint in case that matters.

Any suggestions on how to debug this further? Is there a way to turn on more verbose logging in the GUI?

**Comment by CyberFreek** [comment]
I am having this same problem as well :(

**Comment by noahd1** [comment]
Part of the problem, it seems, is that the URL for the Overview page changed, which is how the tool determined that you were logged in. I attempted to address that in PR #104 but it gets stuck later on in code I'm unfamiliar with.

**Comment by jprouty** [comment]
Thank you all for the report and thanks @noahd1 for the PR for the URL change. I am closing this issue and will make https://github.com/jprouty/mint-amazon-tagger/issues/100 the primary tracking issue for the mint revamp.
