### ISSUE TITLE
Error on Amazon fetch

### ISSUE THREAD

**Issue by trumpetjh** [jprouty/mint-amazon-tagger#105]
Error: Internal error while creating updates: Message: Select only works on < select > elements, not on < span >

**Comment by cwmoriarty** [comment]
+1, can reproduce this. Amazon changed https://www.amazon.com/b2b/reports around a bit.

**Comment by jprouty** [comment]
Thanks for the report. Version 1.45 will fix this, coming out now. Please reopen with additional issues if this isn't the case.
