### ISSUE TITLE
1.45 dropped --mint_input_include_merchant --mint_input_include_mmerchant?

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#106]
Great work on 1.45, working on my dockerized version. CLI dropped these 2 flags, but didn't see it mentioned (haven't looked through the merge closely tho)

`mint-amazon-tagger-cli: error: unrecognized arguments: --mint_input_include_merchant --mint_input_include_mmerchant`

**Comment by jprouty** [comment]
Thanks for asking @cwmoriarty. Please see [this thread for details on what those options do](https://github.com/jprouty/mint-amazon-tagger/issues/50). The arguments in question have been renamed to match the new field names: `--mint_input_include_user_description` `--mint_input_include_inferred_description` respectively.
