### ISSUE TITLE
v1.47 not published to PyPI

### ISSUE THREAD

**Issue by apiology** [jprouty/mint-amazon-tagger#108]
Hi!

I see https://github.com/jprouty/mint-amazon-tagger/releases/tag/1.47 but the latest version published to PyPI is still 1.46: https://pypi.org/project/mint-amazon-tagger/

I'm hoping to get the fix for https://github.com/jprouty/mint-amazon-tagger/issues/107

**Comment by jprouty** [comment]
My apologies! I need to give this a bit more attention as I'm running into issues with the latest version of selenium. If you downgrade to 4.2.0, you should be good to go.

**Comment by jprouty** [comment]
Okay, all good now. selenium-requests has been updated in version 2 and things are all good. I'm making yet another release, as 1.49 that has cleaned up the pinned versions.
