### ISSUE TITLE
Error: Internal error while creating updates: 'Chrome' object has no attribute 'find_element_by_xpath'

### ISSUE THREAD

**Issue by ovitch** [jprouty/mint-amazon-tagger#110]
I get this error when trying to login into Amazon. There is an account selector prompt. 

This happens even if I try to login manually. Will try without the reports to check the Mint tagging part.

**Comment by ovitch** [comment]
I also have the issue when I bypass amazon.

Error: Internal error while creating updates: 'Chrome' object has no attribute 'find_element_by_link_text'

What is your recommendation? Should  I share the exact settings I am using or is this irrelevant at that stage?

**Comment by kevinwheeler** [comment]
+1. Tried using prior releases but then got a different error. Had worked for me in the past.

**Comment by jprouty** [comment]
Thanks kindly for the bug report. I picked up some dependency version updates (to selenium specifically) during the release process without verifying everything was still working. Apologies for the inconvenience. Version 1.50 should resolve your issue.
