### ISSUE TITLE
AttributeError: 'Chrome' object has no attribute 'find_element_by_xpath'

### ISSUE THREAD

**Issue by kevinwheeler** [jprouty/mint-amazon-tagger#112]
Getting the error as shown below. PS thank you for this repo!

-  mint-amazon-tagger
- Running version 1.50
- Creating a new webdriver
- User logging in to Amazon.com
- Login to Amazon.com successful
- Requesting ITEMS report
- Internal error while creating updates: 'Chrome' object has no attribute 'find_element_by_xpath'
- Traceback (most recent call last):
-   File "/Users/kev/programmingStuff/pythonStuff/vendor/amazonMintTagger/venv/lib/python3.9/site-packages/mintamazontagger/main.py", line 629, in create_updates
-     self.do_create_updates(args, parent)
-   File "/Users/kev/programmingStuff/pythonStuff/vendor/amazonMintTagger/venv/lib/python3.9/site-packages/mintamazontagger/main.py", line 679, in do_create_updates
-     if not fetch_order_history(
-   File "/Users/kev/programmingStuff/pythonStuff/vendor/amazonMintTagger/venv/lib/python3.9/site-packages/mintamazontagger/orderhistory.py", line 83, in fetch_order_history
-     request_report(webdriver, report_name, report_type,
-   File "/Users/kev/programmingStuff/pythonStuff/vendor/amazonMintTagger/venv/lib/python3.9/site-packages/mintamazontagger/orderhistory.py", line 192, in request_report
-     webdriver.find_element_by_xpath(

- AttributeError: 'Chrome' object has no attribute 'find_element_by_xpath'
- Internal error while creating updates: 'Chrome' object has no attribute 'find_element_by_xpath'

**Comment by talon256** [comment]
+1 having this same error. Happy to help if anything more than a +1 would be helpful. Thanks, Jeff!

**Comment by jprouty** [comment]
Gah, my bad! Due to my development setup, I was testing while using an older version of selenium, which caused the original issue for version 1.50. Please give this another try on version 1.51 and reopen as needed. Thank you both for the quick feedback on 1.50.
