### ISSUE TITLE
Feature request: Implement CO Retail Delivery Fee

### ISSUE THREAD

**Issue by uofm-matt** [jprouty/mint-amazon-tagger#114]
Colorado implemented a $0.27 delivery fee per order, or not, depending on if the order has sales tax or not.  This makes the tagger not match entries from your credit card because it is off by $0.27 cents.

**Comment by jprouty** [comment]
Thanks for filing. To help inspect what's going on I've placed a small order and selected a CO address. I saw the fee you were describing and will take a closer look at what the amazon data says to see if this is feasible to detect automatically.

**Comment by jprouty** [comment]
Note for myself, [details on the law are here](https://tax.colorado.gov/retail-delivery-fee).

**Comment by jprouty** [comment]
@uofm-matt Hi Matt, I have implemented this feature and it should be functional as of release 1.53. Please try again and let me know if you run into any issues. I'll preemptively close assuming it works.

**Comment by uofm-matt** [comment]
@jprouty I downloaded it and gave it a try and it errored out on me while downloading the csv files.  It's worked before except for the tagging, is it likely on my end?  Attached is the error.
![error](https://user-images.githubusercontent.com/16521836/193155004-12022c81-fa1d-4169-a3d8-81115891188b.png)

**Comment by jprouty** [comment]
What platform/OS are you running on? I'll see if I can replicate

**Comment by uofm-matt** [comment]
Windows 11 with Chrome 106.

**Comment by jprouty** [comment]
I am unable to replicate it myself. Can you attach the logs from `C:\Users\jeffp\MintAmazonTagger\Tagger Logs` (where `jeffp` is your windows user)? Please look for the latest log file that contains logs similar to the error you see in the window. Thanks

**Comment by jprouty** [comment]
After working on https://github.com/jprouty/mint-amazon-tagger/issues/116 tonight, I am convinced you are running into the same issue. Please try 1.54 and see if that helps. Also, it doesn't happen 100% for me, and re-running it up to 4 times should ensure you get through regardless (based on an untested hypothesis). Let me know how it goes!

**Comment by uofm-matt** [comment]
Wasn't sure where you'd like the logs, but here they are.   Still having issues with 1.54 erroring while trying to download the csv files.
[2022-09-30_08-44-23.log](https://github.com/jprouty/mint-amazon-tagger/files/9685610/2022-09-30_08-44-23.log)

**Comment by jprouty** [comment]
Thanks for the logs. Yes, your stack trace is identical to issue https://github.com/jprouty/mint-amazon-tagger/issues/116. Let's keep this issue closed and reopen it if the CO Retail fee functionality doesn't work. Please follow on issue 116 for resolution of the report download issue.
