### ISSUE TITLE
In-app Report for v1.56 on darwin

### ISSUE THREAD

**Issue by davidwbeaty** [jprouty/mint-amazon-tagger#117]
Behavior observed: 

Expected behavior: 

Please attach your log file: /Users/davidbeaty/MintAmazonTagger/Tagger Logs/2022-10-04_11-07-59.log

**Comment by jprouty** [comment]
@davidwbeaty, would you mind attaching the referenced log file, and filing out the expected and actual behavior sections? Thank you

**Comment by davidwbeaty** [comment]
Hi there. A Chrome update had not run yet and when I manually ran that
things appear to be working. Thanks for the tool and for getting back to me
so quickly!

Questions? Comments? I'm as close as your inbox.


David Beaty

voicemail +1 (678) 561-6470
web: davidbeaty.com
Twitter: davidwbeaty
