### ISSUE TITLE
Force refresh of browser to recognize when Amazon reports are ready

### ISSUE THREAD

**Issue by felciano** [jprouty/mint-amazon-tagger#118]
While validating #116, I noticed that sometimes the Chrome browser doesn't refresh automatically to recognize when the Amazon transaction reports were available. After about 5 min, I clicked the refresh button manually and it showed all 3 reports ready. The app picked it up from there to download them and keep processing them.

This is definitel a minor issue, and easy to work around by manually clicking refresh, but a possible fix would be to implement a refresh-pusher every few seconds while in the wait loop.

**Comment by jprouty** [comment]
Thanks for the report; I just noticed this too and will whip something up real quick.

**Comment by jprouty** [comment]
I have added this functionality and it will be available in version 1.57 and later. Thanks
