### ISSUE TITLE
Amazon Issue w/ Order History Reports - "Processing" Indefinitely

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#119]
Not this app, but I'm filing here as this app depends on the backend. `https://www.amazon.com/b2b/reports`  has been stuck "Processing..." reports, no mater how I invoke it.  First seen around 2022-10-19

**Comment by jprouty** [comment]
Thank you for your report! I am also reproducing across all report types.

**Comment by cwmoriarty** [comment]
Looks like has resolved.

**Comment by jprouty** [comment]
I'm still having trouble myself. Let's leave this open a bit longer to help others that may run into this.

**Comment by jprouty** [comment]
My reports are completing now as well. Yay! :)
