### ISSUE TITLE
In-app Report for v1.56 on win32

### ISSUE THREAD

**Issue by Plex-FireWire** [jprouty/mint-amazon-tagger#120]
Behavior observed: 
Crashes when attmpting to start

Expected behavior: Red text in an error window show up moments after start tagging is clicked

Please attach your log file: [2022-10-25_22-35-42.log](https://github.com/jprouty/mint-amazon-tagger/files/9865506/2022-10-25_22-35-42.log)

**Comment by Plex-FireWire** [comment]
I love the tool, not sure waht I did; it did the same thing before and after I downloaded the latest version.

**Comment by jprouty** [comment]
@Plex-FireWire It looks like you needed to update your chrome version to 107 (the latest stable version, which just went out). The error from your logs: `This version of ChromeDriver only supports Chrome version 107
Current browser version is 106.0.5249.119`
