### ISSUE TITLE
In-app Report for v1.56 on darwin - DevToolsActivePort file doesn't exist 

### ISSUE THREAD

**Issue by cluehammer** [jprouty/mint-amazon-tagger#127]
Behavior observed: Using MacOS GUI version.  When using local Amazon reports (initially tried Fetch Reports option providing credentials in app, Chrome launched onto default blank page, not Amazon, and timed out, so tried again with Local Reports option after manual download) with manual Mint login option, a new Chrome window opened to the default blank page, and I received the following pop-up dialog box error: 

Error: Internal error while creating updates: Message: unknown error: Chrome failed to start: exited normally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /Applications/Google Chrome.app/Contents/MacOS/Google Chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
0   chromedriver                        0x0000000109c56f38 chromedriver + 4910904
1   chromedriver                        0x0000000109bd6a03 chromedriver + 4385283
2   chromedriver                        0x000000010981b747 chromedriver + 472903
3   chromedriver                        0x0000000109848930 chromedriver + 657712
4   chromedriver                        0x00000001098444a2 chromedriver + 640162
5   chromedriver                        0x000000010988f460 chromedriver + 947296
6   chromedriver                        0x000000010988ecbf chromedriver + 945343
7   chromedriver                        0x0000000109885ee3 chromedriver + 909027
8   chromedriver                        0x000000010985030c chromedriver + 688908
9   chromedriver                        0x000000010985188e chromedriver + 694414
10  chromedriver                        0x0000000109c241de chromedriver + 4702686
11  chromedriver                        0x0000000109c28b19 chromedriver + 4721433
12  chromedriver                        0x0000000109c3028e chromedriver + 4752014
13  chromedriver                        0x0000000109c2991a chromedriver + 4725018
14  chromedriver                        0x0000000109bfdb02 chromedriver + 4545282
15  chromedriver                        0x0000000109c48888 chromedriver + 4851848
16  chromedriver                        0x0000000109c48a05 chromedriver + 4852229
17  chromedriver                        0x0000000109c5ee5f chromedriver + 4943455
18  libsystem_pthread.dylib             0x00007ff8098784e1 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff809873f6b thread_start + 15

Chrome was already running with multiple windows open when MAT was launched, and did not crash.  The automated window was still open when the error came up, although nothing had changed from the initial launch page display.

Screenshot included, showing the chosen launch options.  Amazon reports were pulled from local Downloads folder, after giving permission to the folder for the MAT app.

Using MacOS Monterey 12.6.2, Chrome 108.0.5359.124 (Official Build) (x86_64)

Expected behavior: Presumably, the Mint website should have been called up in the automated browser window for the tagging process to happen.

Please attach your log file: /Users/btaylor/MintAmazonTagger/Tagger Logs/2023-01-07_21-05-06.log
[2023-01-07_21-05-06.log](https://github.com/jprouty/mint-amazon-tagger/files/10369907/2023-01-07_21-05-06.log)
![Screen Shot 2023-01-08 at 5 27 44 PM](https://user-images.githubusercontent.com/16123594/211228840-155867d7-beab-49bd-9a51-347d95e498ef.png)

**Comment by jprouty** [comment]
Thanks for the report. I am observing this behavior on ubuntu as well. Stay tuned.

**Comment by jprouty** [comment]
Looks like Amazon has changed some of the login flow. I have made some adjustments and the 1.57 and later releases should work for you.

The second issue reported seems to be that a 2nd attempt at "Start tagging" is failing. I'm still looking into this, as this behavior is new. Thanks for that note as well (I have also reproduced this).

**Comment by jprouty** [comment]
I cannot replicate the second issue. Please create a new issue if the retry issue persists for you in version 1.57 and later. Please reopen this issue if you are still having amazon login issues with 1.57+. Cheers
