### ISSUE TITLE
In-app Report for v1.57 on win32

### ISSUE THREAD

**Issue by jnnla** [jprouty/mint-amazon-tagger#129]
Behavior observed: 
Internal error....tagging process stopped on the Amazon website after this error appeared.

Expected behavior: 
Expected no error. I was able to close out and run it again and it proceeded to proceed to mint and tagged things mostly properly, so not sure what this error is about.

Log of issue:

2023-01-13 19:55:23,297 ERROR __main__: Internal error while creating updates: Message: stale element reference: element is not attached to the page document
  (Session info: chrome=109.0.5414.75)
Stacktrace:
Backtrace:
	(No symbol) [0x002A6643]
	(No symbol) [0x0023BE21]
	(No symbol) [0x0013DA9D]
	(No symbol) [0x001409E4]
	(No symbol) [0x001408AD]
	(No symbol) [0x00140B30]
	(No symbol) [0x00173150]
	(No symbol) [0x001669AD]
	(No symbol) [0x0018FD7C]
	(No symbol) [0x0016641F]
	(No symbol) [0x001900D4]
	(No symbol) [0x001A6B09]
	(No symbol) [0x0018FB76]
	(No symbol) [0x001649C1]
	(No symbol) [0x00165E5D]
	GetHandleVerifier [0x0051A142+2497106]
	GetHandleVerifier [0x005485D3+2686691]
	GetHandleVerifier [0x0054BB9C+2700460]
	GetHandleVerifier [0x00353B10+635936]
	(No symbol) [0x00244A1F]
	(No symbol) [0x0024A418]
	(No symbol) [0x0024A505]
	(No symbol) [0x0025508B]
	BaseThreadInitThunk [0x77C46BD9+25]
	RtlGetFullPathName_UEx [0x77E08FD2+1218]
	RtlGetFullPathName_UEx [0x77E08F9D+1165]
	(No symbol) [0x00000000]

**Comment by jprouty** [comment]
Thank you for the report; this has been addressed and fixed in version 1.58. Please reopen if the issue persists or create a new issue if you run into something else. Thanks.
