### ISSUE TITLE
Split transactions don't have notes in them

### ISSUE THREAD

**Issue by noahsw** [jprouty/mint-amazon-tagger#13]
Normal transaction:
![image](https://user-images.githubusercontent.com/2034879/35550880-51cf42c6-0541-11e8-99ca-3364f0d05e4d.png)

Split transaction:
![image](https://user-images.githubusercontent.com/2034879/35550920-82affdb8-0541-11e8-94c8-b3f1e18e09b6.png)

**Comment by jprouty** [comment]
Fact! haha. I have a todo to add them 👍  I'll get to it another day (should be simple, but will take many more requests when saving out to Mint (1 request per line item).

**Comment by jprouty** [comment]
Got it! Nearly a year later :-P sorry about the delay
