### ISSUE TITLE
Ebay tagging feature?

### ISSUE THREAD

**Issue by lucasmbrown-usds** [jprouty/mint-amazon-tagger#135]
This tool is amazing. Would you have any interest in adding support for eBay transactions, too? The same issues apply there.

**Comment by jprouty** [comment]
Hi @lucasmbrown-usds, thanks for filing. Yes, this is certainly something I'd like to tackle in the near future. Please upvote https://github.com/jprouty/mint-amazon-tagger/issues/68 / add your voice there so we have a central spot. Thanks!

**Comment by jprouty** [comment]
Oh, and I'm glad you're finding the tool useful! Cheers
