### ISSUE TITLE
match_transactions() performance limitation

### ISSUE THREAD

**Issue by jamesgo** [jprouty/mint-amazon-tagger#139]
The current "second pass" can be extremely expensive if the number of orders with the same id is high enough. I noticed the tagger was getting hung up (using 64GB RAM for hours at a time), and I narrowed it down to a particular order: I have a 50 item AmazonFresh order that was refunded.

```python
for orders_same_id in oid_to_orders.values():
    combos = []
    for r in range(2, len(orders_same_id) + 1):
        combos.extend(itertools.combinations(orders_same_id, r))
    for c in combos:
        orders_total = sum([o.transact_amount() for o in c])
        amount_to_orders[orders_total].append(c)
```

when len(orders_same_id) is large, the number of possible combinations gets **very** large. I didn't determine the ideal threshold, I believe I only had 2 manifestations of this issue: 50 items and 30 items.

**Comment by jprouty** [comment]
@jamesgo, thanks for the PR. I haven't used AmazonFresh much. To help me better understand how orders are structured, would you be able to donate some example data (PII redacted of course)? I'm curious why a single amazon fresh order would be modeled as such. It would also be great to turn into a few test cases. Thanks! Jeff
