### ISSUE TITLE
Show progress during "Matching Amazon Items with Orders"

### ISSUE THREAD

**Issue by noahsw** [jprouty/mint-amazon-tagger#14]
I tried doing all of my 2016 transactions (~820 orders) and the script seems to hang indefinitely on "Matching Amazon Items with Orders". The python process is at 99% CPU so it's doing something but I can't tell if it's stuck somewhere.

**Comment by jprouty** [comment]
How long does it take for you? For me, it's on the order of 1-2 seconds for ~2k orders

**Comment by noahsw** [comment]
For a couple months of orders it is usually pretty quick. That's why I think it's hanging somewhere because this went for 20+ minutes before I stopped it. I can send you the order file if needed but maybe the trace helps:

```
╰─○ ./tagger.py /Users/noah/Downloads/01-Jan-2016_to_01-Jan-2017\ \(6\).csv /Users/noah/Downloads/01-Jan-2016_to_01-Jan-2017\ \(7\).csv  --no_tag_categories --mint_input_categories_filter=Shopping --mint_email 
Matching Amazon Items with Orders
^CTraceback (most recent call last):
  File "./tagger.py", line 679, in <module>
    main()
  File "./tagger.py", line 80, in main
    amazon.associate_items_with_orders(orders, items)
  File "/Users/noah/Projects/mint-amazon-tagger/amazon.py", line 147, in associate_items_with_orders
    [(Item.sum_subtotals(items), items) for items in item_groupings],
  File "/Users/noah/Projects/mint-amazon-tagger/amazon.py", line 147, in <listcomp>
    [(Item.sum_subtotals(items), items) for items in item_groupings],
  File "/Users/noah/Projects/mint-amazon-tagger/amazon.py", line 403, in sum_subtotals
    return sum([i.item_subtotal for i in items])
  File "/Users/noah/Projects/mint-amazon-tagger/amazon.py", line 403, in <listcomp>
    return sum([i.item_subtotal for i in items])
KeyboardInterrupt
```

**Comment by jprouty** [comment]
Oh interesting! Yes, I might need an example data file to see what's going on. Instead of posting your file, you're welcome to just email me; my email is at the bottom of my webpage: https://www.jeffprouty.com/

**Comment by noahsw** [comment]
@jprouty I sent you an email last week with the attachments. Apologies for the delay!

**Comment by jprouty** [comment]
@noahsw I found the issue and a fix is already in! (The fix isn't ideal: some orders will get dropped, specifically if there's a large number of items (10+) and more than one shipment or charge (2+).)

I also added some neato progress bars that help give a bit more intuition if things are actually frozen, as well as just a great way to visualize # matches, and update progress.
