### ISSUE TITLE
Chrome Driver not right version : In-app Report for v1.61 on win32

### ISSUE THREAD

**Issue by AbsoluteBioTech2** [jprouty/mint-amazon-tagger#141]
Behavior observed: 
Exception thrown (first time run), Chrome driver expects v110, has v 109
Program halts

Expected behavior: 
for it to run without exceptions

Please attach your log file: C:\Users\willm\MintAmazonTagger\Tagger Logs\2023-02-12_15-01-28.log

**Comment by jprouty** [comment]
@AbsoluteBioTech2 I'm guessing you completed a Chrome update and the issue resolved? I just filed https://github.com/jprouty/mint-amazon-tagger/issues/142 to make your life easier going forward.
