### ISSUE TITLE
GUI descriptions

### ISSUE THREAD

**Issue by nquixote** [jprouty/mint-amazon-tagger#144]
Behavior observed:  App GUI doesn't describe that both reports and orders are required for tool to work.

Expected behavior: Tips to guide user to navigate app.

Please attach your log file: /Users/Christopher/MintAmazonTagger/Tagger Logs/2023-02-18_10-01-18.log

**Comment by jprouty** [comment]
Thanks for the report. I have added better error messages coming out in version 1.62 that should make this obvious. Cheers.
