### ISSUE TITLE
Amazon Order History Reports will be sunset after March 20th

### ISSUE THREAD

**Issue by MixMasterMitch** [jprouty/mint-amazon-tagger#147]
On the Amazon Order History Reports page I see a banner saying "Order History Reports will be unavailable after March 20, 2023" Are there any future plans for how this tool will continue to function after March 20?

**Comment by jprouty** [comment]
Thanks @MixMasterMitch for the heads up! This is the first time hearing about the shutdown. I will update the readme to broadcast the announcement.

Amazon has taken this [reporting tooling offline at least once previously](https://github.com/jprouty/mint-amazon-tagger/issues/67) (which was either accidental or wasn't well received by a large account). The fact that they are announcing it this time seems like the end of the road. As I mention in the previous issue I plan on abandoning this tool in it's current form (too clunky and restrictive to only Mint <-> Amazon) and focus my energy on a rewrite.

**Comment by richardbowman** [comment]
I would suggest writing in and complaining also if you haven't already, there is a large conversation going on over in the Tiller community.

https://community.tillerhq.com/t/amazon-order-history-rip/16889/20

**Comment by sandcheeeez** [comment]
This is very upsetting considering that they haven't offered a comparable replacement.

**Comment by jprouty** [comment]
Today is the last day, supposedly. Let's see if they stay true to their word (big tech is either (a) extremely prompt - killing something that sucks to support or (b) extremely lazy/overburdened with process - this tool could be around for years).

I was able to pull 1.25 yrs worth of history just now without problem (it did take about 3 minutes to process).

Thanks @sandcheeeez. I do plan to release a more fully featured tool (and easier to use!), but it won't be ready for some time. Stay tuned!

**Comment by jprouty** [comment]
It seems that Amazon stayed true to their word:
<img width="460" alt="Screenshot 2023-03-21 at 10 44 42 AM" src="https://user-images.githubusercontent.com/51562/226696701-f2fcfcd0-81c3-440e-88b5-bf9478616e8b.png">

**Comment by JimMarquisette** [comment]
It worked for me today (3/21/2023).  Did they turn it back on?


![orderHistory](https://user-images.githubusercontent.com/42503807/226778862-3812fd10-b72c-4d54-8434-58953746e224.png)

**Comment by jprouty** [comment]
Interesting! Still off for me (checked just now).

**Comment by Darida** [comment]
A support agent sent me to https://www.amazon.com/gp/privacycentral/dsar/preview.html which has an option for "Orders". UI says to wait for 5 days. Don't know if format will match yet.

**Comment by jprouty** [comment]
I've done this once before, however, I don't recall ever receiving the promised data export! Please report back.

**Comment by jprouty** [comment]
Bad news first: It's not a plug and play export (ie, this export does not contain 3 files called orders.csv, items.csv, refunds.csv).

Good news: The export has a LOT of additional detail, which should make some things easier (like detecting gift card use and digital content e.g. music and video purchases). Unfortunately, there are two downsides I've found so far:
- No category information per item. The b2b export (Order History Reports) included a UNSPSC per item, which I then manually translated into the basic Mint categories based on the UNSPSC spec and my intuition. You can [see that mapping here](https://github.com/jprouty/mint-amazon-tagger/blob/master/mintamazontagger/category.py#L10-L93). Without this information, itemization is still possible (which is useful) but automatically selecting categories becomes more tricky (they might need to be scraped).
- Only item information is given. No notion of an orders are available. Specifically, I'm looking for the item groupings that make up an amazon "transaction", similar to [this page](https://www.amazon.com/cpe/yourpayments/transactions?ref_=ya_d_l_pmt_mpo).
- Returns are more detailed (yay!) but are missing what item (and it's description) was returned from the order. Additionally, it also doesn't have any category information.

Please chime in if anyone else finds some of this missing information! Thanks

**Comment by straxhaber** [comment]
@jprouty I came here looking for a solution... and shed a tear ;(. I was depending on the Amazon Order Reports and pulling them into a custom accounting reconciliation system I built. You're closer to solving this problem than I am. I'm less interested in the Mint integration, and moreso just the order export. Do you have a prototype of getting Amazon's order history into some sort of machine-readable form after this feature shut-off? (JSON, CSV, etc.) If so, would you be willing to share the source code? I would be eternally grateful.

**Comment by qdmt** [comment]
> @jprouty I came here looking for a solution... and shed a tear ;(. I was depending on the Amazon Order Reports and pulling them into a custom accounting reconciliation system I built. You're closer to solving this problem than I am. I'm less interested in the Mint integration, and moreso just the order export. Do you have a prototype of getting Amazon's order history into some sort of machine-readable form after this feature shut-off? (JSON, CSV, etc.) If so, would you be willing to share the source code? I would be eternally grateful.

Ditto. Less interested in Mint as well, but all for detailed order history.

**Comment by Trevortds** [comment]
Adding to the chorus of people impacted by the loss of this functionality. Amazon tagging was a pretty important part of the way I budgeted. I hope a workaround can be found soon

**Comment by jprouty** [comment]
@straxhaber @qdmt You have two ready to use options for getting a machine readable order history:
1) Official: [Linked by @Darida above](https://www.amazon.com/gp/privacycentral/dsar/preview.html), the data export feature worked for me within a few hours, spanning all order history (15 yrs in my case!).
1) Unofficial: Lots of people seem to use [this extension](https://chrome.google.com/webstore/detail/amazon-order-history-repo/mgkilgclilajckgnedgjgnfdokkgnibi/related?hl=en) (primarily drop shippers it seems).

@Trevortds Thanks for chiming in. I want the functionality back as well! Unfortunately I have a few other projects that are higher on my list at the moment. I'll be coming back to this soon (~weeks).

**Comment by jprouty** [comment]
I am going to close this issue now, as the reporting tool has been sunset (nothing left to track with that regard).

Moving forward, there are two paths I'd like to explore (subscribe to the relevant issue(s) you'd like to follow):

1) [Short term, update this tool to use the Request My Data export](https://github.com/jprouty/mint-amazon-tagger/issues/151).
1) [Long term, create a better tool that works for more things and is easier to use](https://github.com/jprouty/mint-amazon-tagger/issues/150).
