### ISSUE TITLE
Adapt tool to use Amazon's "Request My Data" export

### ISSUE THREAD

**Issue by jprouty** [jprouty/mint-amazon-tagger#151]
Moving info from [the original sunset tracking issue](https://github.com/jprouty/mint-amazon-tagger/issues/147).

Bad news first: It's not a plug and play export (ie, this export does not contain 3 files called orders.csv, items.csv, refunds.csv).

Good news: The export has a LOT of additional detail, which should make some things easier (like detecting gift card use and digital content e.g. music and video purchases). Unfortunately, there are some downsides I've found so far:

1) No category information per item. The b2b export (Order History Reports) included a UNSPSC per item, which I then manually translated into the basic Mint categories based on the UNSPSC spec and my intuition. You can [see that mapping here](https://github.com/jprouty/mint-amazon-tagger/blob/master/mintamazontagger/category.py#L10-L93). Without this information, itemization is still possible (which is useful) but automatically selecting categories becomes more tricky (they might need to be scraped).
1) Only item information is given. No notion of an orders are available. Specifically, I'm looking for the item groupings that make up an amazon "transaction", similar to [this page](https://www.amazon.com/cpe/yourpayments/transactions?ref_=ya_d_l_pmt_mpo).
1) Returns are more detailed (yay!) but are missing what item (and it's description) was returned from the order. Additionally, it also doesn't have any category information.

Please chime in if anyone else finds some of this missing information! It's worth noting I only exported "Your Orders". I am now trying "Request all your data"

**Comment by jon-marsters** [comment]
@jprouty FYI if you order from two different countries you get two sets of data in the download.
for example
Retail.OrderHistory.1/Retail.OrderHistory.1.csv
and
Retail.OrderHistory.2/Retail.OrderHistory.2.csv
hmu if you want any examples

We occasionally order from amazon.co.uk for UK family so the download included a USD set and GBP set

**Comment by jprouty** [comment]
Thanks for the note! I might come back to you for testing/sample data when the time is right.

Cheers

**Comment by cwmoriarty** [comment]
@jprouty as the SME on the CSV format your tool uses, do you have any advice for folks hoping to convert the Amazon export available today to a format that your tool can parse? I think that would give the users a path forward until further development happens.

**Comment by jprouty** [comment]
@cwmoriarty I haven't taken a swing at this yet since downside (2) from above might make this transition more tricky (ie, more inference required during the matching process). Also, I'd love your input on downsides (1) and (3) for you (and from anyone else following along).

For me downside (1) removes a lot of value, as I primarily use it for cashflow analysis by category. Note, (1) can be mitigated for repeat purchases by using mint's renaming/category rules (this is another manual step).

**Comment by ijoseph** [comment]
> For me downside (1) removes a lot of value, as I primarily use it for cashflow analysis by category. Note, (1) can be mitigated for repeat purchases by using mint's renaming/category rules (this is another manual step).

I agree that absent any categorization, this would have no use for me. Not enough of my purchases are repeat purchases to make that workaround useful (and, also, wouldn't that further assume that the price for a given item remained stable, for it to hit Mint's filters?)

**Comment by smenzer** [comment]
This is probably significantly more difficult than it seems, but couldn't you use the Transactions page (https://www.amazon.com/cpe/yourpayments/transactions?ref_=ya_d_l_pmt_mpo) to find matching transactions based on date and amount, and then follow the link to the order to get the items and then split into multiple transactions in mint with the right categories? This would take a lot longer for the script to run, but the pages seem pretty structured so I wonder if it's doable at all?

**Comment by jprouty** [comment]
@smenzer Absolutely. My current planning is to keep this out of scope for this tracking issue and instead push more involved scraping to the [improve tool](https://github.com/jprouty/mint-amazon-tagger/issues/150) that I'd like to get started on.

Also: scraping transactions alone will not divine the categories for the items. That would require another step of scraping the product pages and trying to determine the category (non-trivial) and mapping that back to Mint categories (non-trivial).

@cwmoriarty You're right, something is much better than nothing, which is why I made this tool in the first place. Thank you all for sharing the renewed interest in reviving the tool. I'll give this task some effort and see how quickly we can get something going.

**Comment by jprouty** [comment]
I'll be updating main as I make progress ([like this](https://github.com/jprouty/mint-amazon-tagger/commit/7819f6c55656fde62bcb0ffa666dc9e84c7f2b5e)) since the tool in it's previous formulation no longer provides any value. I will hold off on any releases and PyPI updates until we have a working replacement.

**Comment by jprouty** [comment]
Okay. v1.64 should work and it's in PyPI and built for MacOS in the releases page. I'd love feedback if it's not working/etc. Thanks!

**Comment by hasnolen** [comment]
Amazon: 

> We've received and are processing your request to access your personal data.
> We will provide your information to you as soon as we can. Usually, this should not take more than a **month**. In exceptional cases, for example if a request is more complex or if we are processing a high volume of requests, it might take longer, but if so we will notify you that there will be a delay.

Sheesh… one _month_.

**Comment by jprouty** [comment]
Don't worry! It's typically much faster (30m to a few hours for the orders only export).

**Comment by hasnolen** [comment]
> Don't worry! It's typically much faster (30m to a few hours for the orders only export).

Ah yeah, you're right! Came through in about 2 hours. 

And it worked flawlessly! Beautiful. Thanks so much for these efforts.

**Comment by jprouty** [comment]
Thanks for the note! Glad it worked for you :)

**Comment by felciano** [comment]
I'm trying this new functionality for the first time. The zipfile from Amazon, once available, contains a number of different folders and files, and neigher the UI nor updated readme indicate which one to us. @jprouty, which file should be selected after you click the `Select a File` button in the UI?

```
.../Digital-Ordering.1/
.../Digital.Borrows.1/
.../Digital.Orders.Returns.1/
.../Retail.CartItems.1/
.../Retail.CustomerReturns.1/
.../Retail.CustomerReturns.1.1/
.../Retail.OrderHistory.1/
.../Retail.Orders.ManageYourReturns.1/
.../Retail.Orders&Returns.Concessions/
.../Retail.OrdersReturned.1/
.../Retail.OrdersReturned.Payments.1/
.../Retail.Returns.Receivable.1/
```

**Comment by cwmoriarty** [comment]
@felciano  Select the zip file itself. Do not uncompress it.

**Comment by felciano** [comment]
Thanks @cwmoriarty. Suggested some docs clarification in https://github.com/jprouty/mint-amazon-tagger/pull/157.

Unfortunately also ran into a bug as well: https://github.com/jprouty/mint-amazon-tagger/issues/156

**Comment by josiah-eichelman** [comment]
I have not tried this, but any thoughts on using this tool to automate grabbing Amazon orders?
https://github.com/jbms/finance-dl/tree/master
I'll give it a try tomorrow and see if it still works or if it also was broken by this change.

**Comment by jprouty** [comment]
Thanks for the pointer @josiah-eichelman. That certainly looks helpful but out of scope for this tool. I will be sunsetting this tool as something more robust comes together ie: https://github.com/jprouty/mint-amazon-tagger/issues/150. The finance-dl might be relevant for such a tool.
