### ISSUE TITLE
In-app Report for v1.62 on win32

### ISSUE THREAD

**Issue by sagex2023** [jprouty/mint-amazon-tagger#152]
Behavior observed: 
Error: Internal error while creating updates: Message: session not created: This version of ChromeDriver only supports Chrome version 114 Current browser version is 116.0.5845.97 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	GetHandleVerifier [0x00D7A813+48355]
	(No symbol) [0x00D0C4B1]
	(No symbol) [0x00C15358]
	(No symbol) [0x00C361AC]
	(No symbol) [0x00C31EF3]
	(No symbol) [0x00C30579]
	(No symbol) [0x00C60C55]
	(No symbol) [0x00C6093C]
	(No symbol) [0x00C5A536]
	(No symbol) [0x00C382DC]
	(No symbol) [0x00C393DD]
	GetHandleVerifier [0x00FDAABD+2539405]
	GetHandleVerifier [0x0101A78F+2800735]
	GetHandleVerifier [0x0101456C+2775612]
	GetHandleVerifier [0x00E051E0+616112]
	(No symbol) [0x00D15F8C]
	(No symbol) [0x00D12328]
	(No symbol) [0x00D1240B]
	(No symbol) [0x00D04FF7]
	BaseThreadInitThunk [0x76DC00C9+25]
	RtlGetAppContainerNamedObjectPath [0x77037B1E+286]
	RtlGetAppContainerNamedObjectPath [0x77037AEE+238]

**Comment by jprouty** [comment]
Thank you for the report. I have a revamped version 1.64 coming out shortly which should resolve your issue. Please note that it is now using the 'Request My Data'.

**Comment by jprouty** [comment]
Closing this, as 1.64 and later should resolve this issue. Please reopen if you continue to have an issue.
