### ISSUE TITLE
New version is not compatible on with Mac 13.5.2 (22G91)

### ISSUE THREAD

**Issue by ovitch** [jprouty/mint-amazon-tagger#154]
Hi, just downloaded 1.64 to test it on Mac. I get an error mentioning the app is not compatible with the current version of MacOS. 

I used the DMG version to install. Doesn't seem to be a developer approval limitation - no options to approve it in settings when this occurs.

Error Message is: You can’t open the application “MintAmazonTagger.app” because this application is not supported on this Mac.

Systems report data:
MintAmazonTagger:

  Version:	0.0.0
  Obtained from:	Identified Developer
  Last Modified:	9/8/23, 16:32
  Kind:	iOS
  Signed by:	Developer ID Application: Jeff Prouty (NRC455QXS5), Developer ID Certification Authority, Apple Root CA
  Location:	/Applications/MintAmazonTagger.app

**Comment by cwmoriarty** [comment]
Same issue for me, workaround, install the package from pip:`pip install mint-amazon-tagger --upgrade`

**Comment by jprouty** [comment]
Roger; Thanks for the report. I released this time via a Macbook with ARM64 or "Apple" silicon. I'll need to look a bit closer at how to do this (and PyInstaller in general) in a universal compat way (or offer two versions).

**Comment by jprouty** [comment]
I thought this would be quick, but it appears to be more involved. I'm attempting https://github.com/pyinstaller/pyinstaller/issues/5315#issuecomment-971341261 but need a bit more time to get it figured out.

**Comment by jprouty** [comment]
I might have something workable. Could I ask either of you to try release 1.65: file: MintAmazonTagger_universal2.dmg?

**Comment by jprouty** [comment]
If either of you could try [MintAmazonTagger_Intel.dmg](https://github.com/jprouty/mint-amazon-tagger/releases/download/1.65/MintAmazonTagger_Intel.dmg) that would be appreciated! Thanks.

**Comment by ovitch** [comment]
@jprouty sorry just saw that. Tested it and it works. Will run all the features and revert back.
