### ISSUE TITLE
No Order History Found (In-app Report for v1.65 on darwin)

### ISSUE THREAD

**Issue by talon256** [jprouty/mint-amazon-tagger#155]
Behavior observed: 
Clicked "Export Amazon Data", followed steps until I got a download from Amazon.
Selected the folder after clicking on the button by "Data Export:"
Turns out the folder has to be zipped for it to be selected. So I compressed it.
Selected the compressed Zip file.
"Start Tagging"
Error: Cannot find any order history data in the given Amazon Export.

Expected behavior: 
Not sure why nothing was found. I had expected for it to run something like it used to "back in the day."

Please attach your log file: <<<<LOVE THIS! Thank you!
[2023-09-22_10-19-03.log](https://github.com/jprouty/mint-amazon-tagger/files/12754277/2023-09-22_10-19-03.log)
r Logs/2023-09-22_10-19-03.log

**Comment by jprouty** [comment]
Hi @talon256. Please re-download the zip from Amazon and use that zip verbatim with the tool (ie, do not extract it first).
