### ISSUE TITLE
Transaction' object has no attribute 'description'

### ISSUE THREAD

**Issue by preppietechie** [jprouty/mint-amazon-tagger#158]
Behavior observed: 

GUI threw the following error:Transaction' object has no attribute 'description'

Expected behavior: 

Transactions are exported from Mint and tagged with Amazon purchase data.

[2023-10-13_14-13-32.log](https://github.com/jprouty/mint-amazon-tagger/files/12897284/2023-10-13_14-13-32.log)

**Comment by jprouty** [comment]
@preppietechie Sorry for the delayed response. Were you able to get this tool to work for you or are you still stuck on this issue? I've examined the stack trace and nothing jumps out at me. Considering mint (and this tool) are shutting down at the end of this year, is this still relevant to you? Thanks.

**Comment by jprouty** [comment]
Please reopen if you are still having issue. Cheers
