### ISSUE TITLE
OrderHistory no longer CSV, output is JSON as of 2023-11-01.

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#159]
Amazon's Order History export now is JSON format instead of CSV, ie: `Retail.OrderHistory.1.json`.

It appears Mint.com is being "KilledByIntuit", but I figured I'd log this here.

Thanks for everything @jprouty!

**Comment by jprouty** [comment]
I wasn't planning on addressing this as I've already personally migrated away from mint.

However, if there is any utility to the collective to run it once more I'd be willing to take a look within the next week. Let me know! Thanks

**Comment by jprouty** [comment]
Oh thank goodness 🤣😀!
