### ISSUE TITLE
Appears to get confused by rewards points

### ISSUE THREAD

**Issue by harvimt** [jprouty/mint-amazon-tagger#16]
So, I've confirmed that rewards points don't show up in the CSV, which makes it a real pain to figure out.

here's the order details.

![order](https://user-images.githubusercontent.com/119106/37947855-0f459af4-3142-11e8-8540-9f69d4c1add7.png)

Here's the output of a script I made to parse the CSV and group by order for this order:

```
 '112-2027180-1094604': {
        'items': [
            {
                'Category': 'Wireless Phone Accessory',
                'Item Subtotal': '$61.99',
                'Item Subtotal Tax': '$4.94',
                'Item Total': '$66.93',
                'Title': 'Gamepad for Moto Z - Black',
            },
            {
                'Category': 'Wireless Phone Accessory',
                'Item Subtotal': '$8.96',
                'Item Subtotal Tax': '$0.71',
                'Item Total': '$9.67',
                'Title': 'USB C Charging Dock,LEXEBY1 Sync&Charge Station,Desktop Charger Cradle for OnePlus 5, Nexus 6P/5X, Moto Z/Z Play, Google Pixel XL, LG G5, HTC 10 and A',
            },
            {
                'Category': 'Wireless Phone Accessory',
                'Item Subtotal': '$25.00',
                'Item Subtotal Tax': '$1.99',
                'Item Total': '$26.99',
                'Title': 'RAVPower 60W 12A 6-Port USB Charger Desktop Charger Charging Station with iSmart Technology',
            },
        ],
        'shipments': [
            {
                'Shipping Charge': '$0.00',
                'Subtotal': '$95.95',
                'Tax Before Promotions': '$7.65',
                'Tax Charged': '$7.65',
                'Total Charged': '$94.59',
                'Total Promotions': '$9.01',
            },
        ],
    },
```

So the tagger is looking for a $94.59 transaction, but it's not to be found, only the $66.93 of "real money" I actually paid.

I've already created a wrapper script that downloads the CSV reports, could I add a new shipment to the order that just has promotions, so the total charged is negative? or would I need to doctor each shipment?

Or should I create a new csv with rewards points spending in them? I haven't actually looked at the tagging code that much, so I'm not sure how hard this is to fix (feels kinda hard)

**Comment by jprouty** [comment]
Hi Mark!

First off, I can tell you're a power user based on all the types of credits/promos you've got going on. Please let me know if you run into any other weird edge cases.

Unfortunately, Amazon's order reports are not the most expressive... in this case they do not provide the multiple payment instruments, and how much was charged to each. This is (sometimes, not always though!) broken out if you grab the individual invoice from Amazon. Sometimes it's also shown as a gift card.

I haven't found a programmatic way to figure this out, but let me know if you have any ideas.

Me personally, I've stopped using reward credits towards purchases, as that amount doesn't qualify towards future points earned (whereas, if you get the cold hard cashback, then used that to pay off the card, that [_does_ count towards more points](https://money.stackexchange.com/a/41839)).

**Comment by harvimt** [comment]
That's good advice. I'll keep that in mind, I'll just manually split these few transactions, and then apply points as statement credit in the future.

**Comment by jprouty** [comment]
Sorry for the inconvenience :( I'll close this issue for now.
