### ISSUE TITLE
single item orders with promotions do not get recategorized

### ISSUE THREAD

**Issue by elgoldman** [jprouty/mint-amazon-tagger#17]
https://github.com/jprouty/mint-amazon-tagger/blob/0d8a8ef102f5a5caad5f922babf51a1c2b9deb7e/tagger.py#L202-L204

https://github.com/jprouty/mint-amazon-tagger/blob/0d8a8ef102f5a5caad5f922babf51a1c2b9deb7e/mint.py#L199-L202

orders with subscribe and save show up as a single item order with a 5% promotion discount, resulting in a single item, but multiple transactions, in this case, the default category is used.

**Comment by jprouty** [comment]
Hi @elgoldman. Are you using `--verbose_itemize`? I'm a bit confused on what behavior you're seeing vs what you're expecting. Can you clarify? Thanks!

**Comment by elgoldman** [comment]
thanks @jprouty, you are right, using --verbose_itemize  does result in the behavior I'm looking for.  I'm curious why this isn't the default behavior? If you order one shirt and have a category mapping from 'Apparel' on Amazon to 'Clothing' in Mint, why would you want it to not get recategorized just because there was a promotion?

the behavior I'm seeing (without --verbose_itemize) is this:

Case#1: the order has one item and no promotions. the mint transaction will get recategorized.
Case#2: the order has one item and a promotion. the mint transacction will NOT get recategorized.

maybe there's some use case I'm just not thinking of, where this would be desirable, but I would expect if you wanted to assign a category in one case you would want it in the other as well.

thanks for developing this great tool!

**Comment by jprouty** [comment]
@elgoldman I hear you! I think I've got a fix for you (I also just added a shit ton of unit tests). Give that a shot. I'm closing for now; feel free to reopen or file new issues if it's not working as expected! Thanks for your feedback!
