### ISSUE TITLE
bash: ./tagger.py: No such file or directory

### ISSUE THREAD

**Issue by ltjdym** [jprouty/mint-amazon-tagger#18]
After downloading item.csv I enter the following command I get this error. Am I supposed to save the .csv in aparticular directory or should I change my directory before entering the command? Like cd/?

admin@ubuntu_1604:~$ ./tagger.py Items.csv --dry_run --mint_email mydjtl@gmail.com bash: ./tagger.py: No such file or directory

**Comment by jprouty** [comment]
Yes, you need to cd into the directory where you cloned this repository. I usually move my items/orders csvs into the same directory as the source, which makes it fool proof and easy to write the cmd line args.

At the moment, I don't have a pypi setup or anything fancy that adds tagger to bin/PATH or similar.

**Comment by ltjdym** [comment]
Gotcha. I'm using Ubuntu on QNAP. Don't quite know how to cd into the right directory :( but my problem not yours. thanks for your help
