### ISSUE TITLE
Feature Request: build in support for non-US Amazon instances

### ISSUE THREAD

**Issue by felciano** [jprouty/mint-amazon-tagger#22]
It would be nice for this to work for folks who travel and occasionally buy from non-US-based Amazon instances. I expect this may require some smarts in the prefix used when renaming items (e.g. "Amazon.co.uk: " instead of "Amazon.com: ") and the subsequent use of those tags to identify previously processed items.

**Comment by jprouty** [comment]
I don't know what non-US data looks like. Is the format different? Does amazon export US w/ non-US transactions together? Or separately? Or is it just that you want them labeled based on the domain they were purchased from?

**Comment by jprouty** [comment]
It looks like both Items/Orders have a "website" column, which for me being US, shows "Amazon.com". That column could be used as the prefix.

**Comment by jprouty** [comment]
A commit is coming in hot for this. Will just work be default based on the website column
