### ISSUE TITLE
Retagging isn't saving back to Mint

### ISSUE THREAD

**Issue by felciano** [jprouty/mint-amazon-tagger#23]
I just tried the retagging functionality and it seems to correctly find items that warrant re-tagging, but the results are not persisted back to Mint. I tried with both `--retag_changed` and `--prompt_retag`. Two things I noticed in the failure cases:

1. These are entries previously processed with `mint-amazon-tagger`:  their descriptions start with "Amazon.com: " and were categorized (by me) under a custom Mint category called "Amazon Purchases". `mint-amazon-tagger` correctly finds them and recommends smarter categories (e.g. Books).
2. I haven't done a comprehensive sweep, but it looks like all of the failure case entries seem to be single item purchases (i.e. no splits).

**Comment by jprouty** [comment]
Let me take another look; last time I did tagging I do remember retagging working for me, but I think I did just a --retag_changed and let it fly.

**Comment by jprouty** [comment]
Ah ha! I found it. The category logic is a bit messed up for all single item transactions (non-splits). Even not retagging... which means retagging will never really commit those changed categories. Fix should be ready soon
