### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by sandinmyjoints** [jprouty/mint-amazon-tagger#25]
@jprouty Thanks so much for creating this project. It'd be great if you could specify a license for it -- there's some excellent guidance on choosing one and specifying it in your repo:
- https://choosealicense.com/
- https://help.github.com/articles/licensing-a-repository/

**Comment by jprouty** [comment]
Thanks William! I've added MIT

**Comment by sandinmyjoints** [comment]
Thanks @jprouty !

**Comment by jprouty** [comment]
Just curious, did you have anything in mind WRT using this repo for a new project?

**Comment by sandinmyjoints** [comment]
I had two things in mind that led me to ask for you to choose a license:
1) a general rule I try to know the license of software I use -- just a good rule of thumb for preventing problems!
2) I think a product possibly could be built around this backend, but if the licensing forbid it, then that would be the end of that. (Will I ever actually make such a product? Highly unlikely -- I have zero free time and this idea is somewhere in the middle of a long list of future projects. But at least I now know not to scratch it off the list due to licensing.) (You should totally make a product around it yourself, btw!)

**Comment by jprouty** [comment]
Ya, I really want to do (2) as it would be the best way to promote the project and get the most # of people using it. But.... it's pretty difficult considering how cumbersome the transaction export (or scraping) that would be necessary (specifically AMZN) in conjunction with storing/retaining sensitive credentials to automate the process.

**Comment by sandinmyjoints** [comment]
Yup, it's definitely got some challenges. I wondered if the credentials problem could be handled by creating an agent to run on user's own machines, pull transaction data using their credentials locally, then ship the data to a service to be cleaned up, tagged, transformed, etc. That way the credentials never need to leave the user's machine.
