### ISSUE TITLE
Feature request: auto-download orders info from Amazon

### ISSUE THREAD

**Issue by noahsw** [jprouty/mint-amazon-tagger#26]
This tool is amazing but it's a big pain to login to Amazon and download the orders info -- especially because I have to do it for both myself and my wife's account.

Similar to how you can provide Mint login info to the CLI, it'd be amazing if you could provide Amazon login to CLI and all the orders info would be downloaded automatically!

**Comment by yoehoehne** [comment]
I had the same thoughts! It's perfect except for having to download the amazon transactions!

I'm no python programmer, but I created a simple MVP that takes the credentials, logs into Aamzon and downloads your orders and items for the past 30 days. I could probably submit a PR if that's something others are interested in.

**Comment by jprouty** [comment]
Totally agree! It's something I've thought a lot about and haven't found a compelling solution.

There's 3 approaches that I can think of:
1. **Use Amazon's API "Marketplace Web Service (MWS)"** See [ref here](http://docs.developer.amazonservices.com/en_US/orders-2013-09-01/Orders_ListOrders.html). This requires each person who wants this functionality to sign up for a "business" account. I personally tried to do this with somewhat vague information and was not given an account :( Even if this worked, the API endpoints we need are highly rate limited (on the order of GetOrder being 1 request a minute!)
2. **Scrape the Amazon orders page** Not the bulk/order history section, but the standard orders that humans look at under "My orders". To get the level of detail needed, the detailed order page is required for each order (the summary isn't enough). Furthermore, a scraper would need to be written and maintained to parse the actual order detail page itself (as well as the list of orders). Keeping this functional would be a decent amount of work. Furthermore, this too isn't a viable option as the order detail pages are rate limited (try loading 10 at once, and you'll start to see it).
3. **Automate Amazon login and download order history for you** This is the only option that is likely viable. It would work by: (a) give the cmd the amazon credentials, it does a similar thing as to mint (opens a browser, allows for you to answer any auth challenges, etc). (b) auto-navigates to the order history page on success (c) auto-requests the 3 needed order history reports (d) waits until they are done processing (e) downloads the 3 reports (f) continues running the script as per usual. I'm thinking by default only get the **last 6 months** of activity, which could easily be overridden by command line

@noahsw Would (3) make your life easier?

**Comment by noahsw** [comment]
Yep! Option 3 definitely seems like the way to go. As long as this project remains open source, I don't mind providing my credentials to the CLI. 

Once logged into Amazon, do you actually need to navigate the pages or can you simply fire the POST requests to get those CSVs?

**Comment by jprouty** [comment]
And by maybe there are bugs, nothing that would destroy your amazon or mint accounts :-P Should be safe, but something might be brittle in the flow that may stall out or break.

**Comment by noahsw** [comment]
@jprouty 

```
WASEA-MLVSTNSW:mint-amazon-tagger noahsw$ ./fetch_and_tag.py --no_tag_categories --mint_input_categories_filter=Shopping --mint_email hidden@hidden.com --dry_run
Amazon email: hidden@hidden.com
Amazon password:
Traceback (most recent call last):
  File "./fetch_and_tag.py", line 352, in <module>
    main()
  File "./fetch_and_tag.py", line 54, in main
    name = args.amazon_email.split('@')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

Looks like a simple fix =)

**Comment by jprouty** [comment]
Whoops! Fix is not yet in, as I refactored everything and am getting ready this ready for a PyPI package (so you can just `pip3 install mint-amazon-tagger` and `mint-amazon-tagger ...` anywhere!

In the meantime, try doing --amazon_email youre_email@whatever.com. Should get you over this hurdle at least!

**Comment by jprouty** [comment]
Okay, PyPI should be rocking. Do you mind trying via the new instructions? Just take a look at the project home/readme and use pip!

**Comment by noahsw** [comment]
New install worked great! It goes farther now. Browser opens up to Amazon, enters my email address, and then I get this error. It didn't try entering my password.

```
Logging into Amazon \Traceback (most recent call last):
  File "/usr/local/bin/mint-amazon-tagger", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 61, in main
    start_date, end_date, args)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/orderhistory.py", line 58, in fetch_order_history
    session_path=args.session_path)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/orderhistory.py", line 179, in get_amzn_driver
    driver.find_element_by_id('ap_password').send_keys(password)
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 478, in send_keys
    {'text': "".join(keys_to_typing(value)),
  File "/usr/local/lib/python3.7/site-packages/selenium/webdriver/common/utils.py", line 150, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'NoneType' has no len()
```

**Comment by jprouty** [comment]
@noahsw Please try again! `pip install --upgrade mint-amazon-tagger`

**Comment by noahsw** [comment]
Success!!! So cool. Super awesome that I can run it multiple times with various flags and it doesn't need to re-download the Amazon reports! Nice touch.

A couple minor things about the command line output:

```
Missing Items/Orders History csv. Attempting to fetch from Amazon.com.
Logging into Amazon -Amazon password:/
/Having trouble logging into Amazon. Please see the browser and complete login within the next 5 minutes. This script will continue automatically on success. You may need to manually navigate to: https://www.amazon.com/gp/b2b/reports
Hint: Looks like an OTP challenge!
/
Requesting Items report /
Waiting for Items report to be ready |
Downloading Items report |
Requesting Orders report -
Waiting for Orders report to be ready \
Downloading Orders report |
Requesting Refunds report |
Waiting for Refunds report to be ready |
Downloading Refunds report \

All Amazon history has been fetched. Onto tagging.
Parsing Orders - 24
Parsing Items - 30
Parsing Refunds -
Dry Run; no modifications being sent to Mint.

Creating Mint Category Map.
Fetching Categories \Mint password:-
Logging into Mint \Please enter your 6-digit MFA code:\
```

# It doesn't seem to be printing new lines when it should.
# I don't know what an "OTP challenge is"
# It was unclear that I should enter my MFA code into the terminal. I entered it into the web browser and the terminal was stuck until I realized I had to hit [enter]
