### ISSUE TITLE
issue with tax calculation?

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#27]
Got 16655 transactions and 128 categories from Mint in 00:01:27
Backing up Mint to local pickle file, epoch: 1548573005 |
Matching Amazon Items with Orders |████████████████████████████████| 2638/2638
Matching Amazon Orders w/ Mint Trans |█████████████████████████████   | 2215/2446

Determining Mint Updates |████████████████▏               | 1109/2191
Traceback (most recent call last):
  File "./tagger.py", line 914, in <module>
    main()
  File "./tagger.py", line 135, in main
    mint_category_name_to_id)
  File "./tagger.py", line 323, in get_mint_updates
    if order.attribute_itemized_diff_to_per_item_tax():
  File mint-amazon-tagger/amazon.py", line 350, in attribute_itemized_diff_to_per_item_tax
    self.items[adjust_idx].item_subtotal_tax += adjust_amount
TypeError: list indices must be integers or slices, not NoneType

**Comment by jprouty** [comment]
Thanks for the bug report. Do you mind helping me debug? I made some modifications to amazon.py in a branch. Assuming you cloned my repo directly (no forking) you should be able to do:

0. Make sure you stashed/committed any local changes. If you haven't touched any files, **ignore this**
1. `git checkout origin/jprouty-cwm-tax-issue`
2. Run the tagger as you were before
3. Post the output after the last "Sales tax adjustment debugging:" (you might have a bunch of spam; we only care about the last time this method is called).
4. Return to the master branch: `git checkout master` && `git pull` to update

**Comment by jprouty** [comment]
@cwmoriarty, any chance you can try the above?

**Comment by jprouty** [comment]
Closing for now. Thanks
