### ISSUE TITLE
Hang when supplying --order_history_num_days

### ISSUE THREAD

**Issue by aschmois** [jprouty/mint-amazon-tagger#32]
Trying to get the last 450 days gets stuck. No error thrown. The items report is downloaded but never moved into the AMZN Reports directory, it only moves an empty csv. Not supplying the parameter works no problem.

**Comment by jprouty** [comment]
Thanks for the bug report! This auto-download feature on the AMZN side is new functionality, and apparently still has some kinks to work out.

Can you try:
1) Remove the empty csv file(s)
2) Retry the automated fetch
3) Watch what happens in the browser

Let me know: 
a) how many reports are requested
b) where/if the process stops in the workflow (see below)
c) what the resulting files are

You should see it attempt to request a report, wait for it to be ready, then downloads it (in the background/terminal; it _should_ happen 3 times, once per: Items, Orders, Refunds.

**Comment by aschmois** [comment]
From a clean start:

1. The browser starts
2. Logs into amazon
3. Generates the first report with the correct days and description
4. Chrome auto downloads the first report (after being generated)
5. No other reports downloaded or requested
6. The AMZN Reports has the items report but empty
7. Program does nothing else

**Comment by jprouty** [comment]
Great; thanks for the detail and I'll see if I can replicate tonight.

**Comment by jprouty** [comment]
I just tried to replicate on windows and think I found the issue. If you look in the terminal, I'm guessing you'd see some error about 'charmap' codec can't encode character...

**Comment by jprouty** [comment]
Okay; I think I tracked down the issue. Please update at or beyond 1.11 and try again!

**Comment by aschmois** [comment]
Issue fixed confirmed!
