### ISSUE TITLE
ValueError: binary mode doesn't take an encoding argument

### ISSUE THREAD

**Issue by briansea** [jprouty/mint-amazon-tagger#34]
First let me say, i'm very thankful you made this tool. I think it will be super helpful!

I'm getting the following error when trying to download from mint

`Fetching Transactions |
Backing up Mint to local pickle file, epoch: 1551109258 \Traceback (most recent call last):
  File "/usr/local/bin/mint-amazon-tagger", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 131, in main
    args.mint_pickle_location)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 297, in dump_trans_and_categories
    with open(trans_pickle_path, 'wb', encoding='utf-8') as f:
ValueError: binary mode doesn't take an encoding argument`

What should I do to fix it?

Thank you,
Brian

**Comment by briansea** [comment]
I removed the encoding params on this line and the following and it seems to work. But I'm not confident enough to make a PR. :)

**Comment by jprouty** [comment]
Whoops. My bad. Fixed. Please update to version 1.12 or later!

And yes, you're very correct on your fix 👍

**Comment by briansea** [comment]
Thank you!  Hey, do you have a tip jar / wish list anywhere? I'm very thankful for this tool!

**Comment by jprouty** [comment]
@briansea The compliment is more than enough! I'm just glad people are finding it and actually using it 👍 

Random question, have you ever tried [Personal Capital](https://www.personalcapital.com/)? There is a similar API for connecting with PC and I was thinking about adding support.

**Comment by briansea** [comment]
I've looked at it, but it seems to have less good budgeting tools than Mint? So, for now, I'm staying on Mint. It has several things I wish were different, but it's free and I haven't found something better for my needs yet.  Thanks for asking!
