### ISSUE TITLE
Syntax error when running any command

### ISSUE THREAD

**Issue by reharik** [jprouty/mint-amazon-tagger#35]
Hi, I don't really know python, so I may have something installed wrong, but when I run any command I 
I'm running mint ( ironically ) linux which is based off of ubuntu 18 I believe.  Not sure what other diagnostics to provide please let me know and I will do so.
Thanks
get a syntax error. Here's the stack trace outputted.
```
 mint-amazon-tagger --help
/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/local/bin/mint-amazon-tagger", line 11, in <module>
    load_entry_point('mint-amazon-tagger==1.12', 'console_scripts', 'mint-amazon-tagger')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2408, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2414, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/mintamazontagger/main.py", line 27, in <module>
    from mintamazontagger.mintclient import MintClient
  File "/usr/local/lib/python2.7/dist-packages/mintamazontagger/mintclient.py", line 112
    **modify_trans,
     ^
SyntaxError: invalid syntax

```

**Comment by jprouty** [comment]
Hi Raif,

It looks like you are running with python2.7. this library only supports
python 3 onwards. I would recommend upgrading your install. What operating
system are you using?

**Comment by reharik** [comment]
I thought it might be something to like that.  I'm using mint ( ubuntu 18 ) which does come with python 3.  but pip3 wasn't working.  I uninstalled pip3 and reinstalled it then it was working.  So I then did
`pip uninstall mint-amazon-tagger`  to get rid of whatever might be the result of pip 2.7 install.  Then I did pip3 install as per instructions.  Now I'm getting a new error.  Initially I saw that it was using a cached call so I disabled cache and here's what I"m getting
`  ~ pip3 --no-cache-dir install mint-amazon-tagger
Collecting mint-amazon-tagger
  Downloading https://files.pythonhosted.org/packages/11/29/742a68a367aed9e7c6ad802290adc45b78bdaf0fe9cbdac8cfbd769ff122/mint_amazon_tagger-1.12-py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 908kB/s 
Collecting readchar (from mint-amazon-tagger)
  Downloading https://files.pythonhosted.org/packages/ef/f3/50cc9199733bf91f3c140150752a6430d8b785f9d22a31dcae721edb0b9a/readchar-2.0.1-py3-none-any.whl
Collecting keyring (from mint-amazon-tagger)
  Downloading https://files.pythonhosted.org/packages/29/54/22d12573bae3cccd1fb9ead7f69409257be16f7bdd7281f939b035a76399/keyring-19.0.1-py2.py3-none-any.whl
Collecting outdated (from mint-amazon-tagger)
  Downloading https://files.pythonhosted.org/packages/86/70/2f166266438a30e94140f00c99c0eac1c45807981052a1d4c123660e1323/outdated-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-26__gazw/outdated/
You are using pip version 8.1.1, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
`
The last line is odd.  I'm hesitant to do the command because it's using "pip" rather than "pip3"

**Comment by jprouty** [comment]
Oh wow, very old version of pip! Try pip3 install --upgrade pip

**Comment by reharik** [comment]
HI, I did do the upgrade and am now on v 19.0.3.  However I get the same error upon trying to install

**Comment by jprouty** [comment]
You may also need to do:

sudo apt-get install -y python3-setuptools

**Comment by reharik** [comment]
Hi, I finally managed to get it to install.
It's interacting with amazon find getting the reports.  Mint not
surprisingly is sucking I"m getting this error once the mint landing page
loads
Traceback (most recent call last):
  File "/home/reharik/.local/bin/mint-amazon-tagger", line 10, in <module>
    sys.exit(main())
  File
"/home/reharik/.local/lib/python3.5/site-packages/mintamazontagger/main.py",
line 124, in main
    mint_category_name_to_id = mint_client.get_categories()
  File
"/home/reharik/.local/lib/python3.5/site-packages/mintamazontagger/mintclient.py",
line 70, in get_categories
    mint_api = self.get_mintapi()
  File
"/home/reharik/.local/lib/python3.5/site-packages/mintamazontagger/mintclient.py",
line 56, in get_mintapi
    headless=self.headless)
  File "/home/reharik/.local/lib/python3.5/site-packages/mintapi/api.py",
line 339, in create
    return Mint(email, password, **opts)
  File "/home/reharik/.local/lib/python3.5/site-packages/mintapi/api.py",
line 335, in __init__
    imap_folder=imap_folder)
  File "/home/reharik/.local/lib/python3.5/site-packages/mintapi/api.py",
line 410, in login_and_get_token
    imap_folder=imap_folder)
  File "/home/reharik/.local/lib/python3.5/site-packages/mintapi/api.py",
line 261, in get_web_driver
    status_message = driver.find_element_by_css_selector(".SummaryView
.message")
  File
"/home/reharik/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py",
line 598, in find_element_by_css_selector
    return self.find_element(by=By.CSS_SELECTOR, value=css_selector)
  File
"/home/reharik/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py",
line 978, in find_element
    'value': value})['value']
  File
"/home/reharik/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py",
line 321, in execute
    self.error_handler.check_response(response)
  File
"/home/reharik/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py",
line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such
element: Unable to locate element: {"method":"css
selector","selector":".SummaryView .message"}
  (Session info: chrome=67.0.3396.99)
  (Driver info: chromedriver=2.41.578700
(2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.10.0-38-generic
x86_64)


It sucks that you have to scrape the damn sight to automate anything.  Glad
you did it rather than me. :)  You might look at cypress.io as an
alternative to selenium as it's much more deterministic.  I don't know if
it has the proper apis though.

In any case does this error make sense or is it expected? Is there anything
I can do?
R

**Comment by reharik** [comment]
I should say it throws this error after it get's to the logged in landing page.  So it opens the browser, logs in lands on the "overview" page then selenium pukes.

**Comment by jprouty** [comment]
It would appear that the error is coming from the underlying MintAPI, specifically this line:
https://github.com/mrooney/mintapi/blob/master/mintapi/api.py#L268

It's looking for a status message at the bottom of the mint page after you have successfully logged in, saying that it's fetching the latest details from your accounts.
- Do you have any accounts currently syncing w/ your mint account?
- Do you see this status bar at the bottom of your mint page (either using this tool or just manually logging in)?
- It'd be great to be able to disable the "wait for sync" but it seems that was not allowed as part of the API (by accident). I can try to get a PR into MintAPI and integrate that feature through (would help debug this case, possibly).

**Comment by reharik** [comment]
Hi, I'm not sure what you mean by "accounts currently syncing wi/ your mint account"  I don't have any that are having trouble syncing .i.e. saying the password didn't work or it needs 2 part auth.  All my accounts are able to connect fine.  I don't know if mint automatically syncs all accounts when you login, I would thing so but it doesn't give any indication of that.  So I'm not sure about number 1.
I don't see any status bar at the bottom either visually or in dev tools.  I search for .SummaryView and it's present in a style tag, but not in any element.
regarding wait for sync, yes that does seem to be the problem.  This is what sucks about writing an api based off of scraping, as soon as the target makes any changes on their page, things start breaking in your api.  It sucks even further, and tremendously that mint is too lame to publish an actual api.  
Anyway, let me know if there is anything I can do to assist.  Perhaps I'll build locally and remove the "wait_for_sync" clause.  I wish this were written in node :) 
Thanks again,
Raif

**Comment by jprouty** [comment]
Interesting! There could be a class of accounts that have a different UI treatment or something related to the sync bar at the bottom.

Regardless, I have a change out to the [MintAPI folks ](https://github.com/mrooney/mintapi/pull/173) that should resolve your issue. I was also running into some weird timing issues (related to the sync bar, and how selenium does waiting).

As you've already mentioned, there really is no other option to scrapping. If it makes you feel better, Mint itself is entirely built on scrapping (and is slowly getting banks to move onto actual APIs). [Yodlee](https://en.wikipedia.org/wiki/Yodlee) was the original backend for Mint, and I believe Intuit has created their own in-house since. Anyway, welcome to the jungle :)

**Comment by reharik** [comment]
Hi, my python is non existant, but could you not do add "wait_for_sync=False"  to the list of params here?  It looks like the mintApi init takes that param ( but Im looking at the mintapi in your github account, I thought you wrote it ). 
https://github.com/jprouty/mint-amazon-tagger/blob/a3e5b67cafe005bf02e21f51bb935db1d83f2587/mintamazontagger/mintclient.py#L53

**Comment by jprouty** [comment]
I wrote this program (mint-amazon-tagger) and have made a few contributions to MintAPI when it needs attention (did not author it). MintAPI requires some additional changes to support passing that boolean in through the create method. My PR (linked above) includes the ability to pass that through; however, the PR itself should resolve the issue you're having altogether.

**Comment by reharik** [comment]
ok cool, I guess I should just subscribe to that pr and check it out when it resolves.  Should I uninstall mint-amazon-tagger and re install it when the new version of the api comes out? I don't really know how python handles dependencies.
Thanks,
R

**Comment by jprouty** [comment]
Raig, sorry for the delay. I've just finally exposed the wait_for_sync, and defaulted it to off. I'll be updating the package shortly. To update this tool, you can simply run:
`pip3 install --upgrade mint-amazon-tagger`
