### ISSUE TITLE
Trying to run, but fails... any idea?

### ISSUE THREAD

**Issue by WalterGandra** [jprouty/mint-amazon-tagger#44]
hey guys,

When I try to run, it asks my email and I successfully can log into amazon... but then, it tries to get the reports and nothing happen... any idea on what I am doing wrong?

![image](https://user-images.githubusercontent.com/40674112/64913319-ad15a600-d70b-11e9-92b7-6e67724559e9.png)

![image](https://user-images.githubusercontent.com/40674112/64913321-b9016800-d70b-11e9-9605-8efc18471b69.png)

![image](https://user-images.githubusercontent.com/40674112/64913322-bdc61c00-d70b-11e9-9bb8-e3a0f325db02.png)

Thanks,

Walter

**Comment by jprouty** [comment]
Hi Walter! Thanks for using the tool (or trying to at least).

It sounds like you're super close; something just isn't quite right. How are you running the mint tagger? Specifically, I don't recognize the win10 terminal you're using to launch it. I have run on windows 10 with no problems on my home PC, using the builtin PowerShell. 

Another thought: do you have an exotic network setup? Using a proxy or anything similar?

The error message you're getting appears to be related to how the python program communicates with the chromium web browser that's used for scrapping. Feel free to do a web search; there's a few interesting results, but nothing that stood out that's a general coding error/etc.

**Comment by WalterGandra** [comment]
Hey Jeff,

Thanks for the answer! I made a lot of progress just changing it to
powershell! I was using a python IDE before...

I made progress, but it gets stuck on this step when trying to make the
changes in Mint - see that I could login though... for some reason, it
opens a second tab and stays processing...

By the way, thanks a lot for the hand! Cheers!

[image: image.png]

[image: image.png]

[image: image.png]

**Comment by jprouty** [comment]
@WalterGandra Sorry for the slow response. It looks like the images are gone (maybe I was too slow?).

Are you still having trouble? Let me know what you're getting stuck on and let's see if we can get you across the finish line! (make sure you have the latest version, as there was an issue with making updates to mint relating to itemization; recently fixed!)

**Comment by WalterGandra** [comment]
Hey Jeff,

Thanks for getting back to me! I Will update it tomorrow... but I think my
issue may be different... it downloads all the files from amazon, but gets
stuck on mint...

See the screenshot below... it gives me an error -100. Thanks for the help!

**Comment by jprouty** [comment]
For some reason I'm having trouble seeing your screen shots; do you mind emailing me directly: jeff.prouty@gmail.com

**Comment by jprouty** [comment]
Walter; I hope you were able to get this running. My only other suggestion at this point would be to completely uninstall and re-install python3 on your system. Maybe something is slightly offer, specifically possibly your selenium setup. Anyway, I'm not sure there's much more I can help with on this specific issue thread. I'll leave it open just incase someone else runs into this and may even find a fix!
