### ISSUE TITLE
Feature request: categorize returned items the same as original purchase

### ISSUE THREAD

**Issue by felciano** [jprouty/mint-amazon-tagger#45]
It looks like `mint-amazon-tagger` recognizes and imports Amazon returns correctly, but seems to categorize them as "Returned Purchases". As a result, if you do summations on the transactions by category, you will incorrectly include the original purchases, even though they were returned. 

Instead, it would be nice if `mint-amazon-tagger` instead matched the return with the original purchase (looks like the descriptions are identical) and categorized them the same way. That way a $9.50 purchases for a Book that was then returned would show up as a $9.50 credit under Book, effectively nulling out the transaction under the same category.

**Comment by jprouty** [comment]
Great idea! Let me verify that I'm seeing the same thing on my history and I'll take a look at how hard this would be to get going.

**Comment by jprouty** [comment]
Finally looking into this. Related to #61, this is now a bit trickier :) But I think it should be pretty easy: use the item name + order id to look up from the items report and pull out the UNSPSC Code and use the new categorization taxonomy.
