### ISSUE TITLE
Error parsing orders

### ISSUE THREAD

**Issue by briansea** [jprouty/mint-amazon-tagger#47]
Hello!

Thank you so much for the helpful app!

I've started having an issue, shown below. Do you have any ideas

Missing Items/Orders History csv. Attempting to fetch from Amazon.com.
Logging into Amazon.com
Amazon password: 
Requesting Items report |
Waiting for Items report to be ready |
Downloading Items report -
Requesting Orders report \
Waiting for Orders report to be ready |
Downloading Orders report |
Requesting Refunds report \
Waiting for Refunds report to be ready /
Downloading Refunds report \

All Amazon history has been fetched. Onto tagging.
Parsing Orders - 55
Parsing Items - Traceback (most recent call last):
  File "/usr/local/bin/mint-amazon-tagger", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/main.py", line 86, in main
    items_csv, ProgressCounter('Parsing Items - '))
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/amazon.py", line 453, in parse_from_csv
    return parse_from_csv_common(cls, csv_file, progress)
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/amazon.py", line 75, in parse_from_csv_common
    if is_empty_csv(csv_file):
  File "/usr/local/lib/python3.7/site-packages/mintamazontagger/amazon.py", line 71, in is_empty_csv
    open(filename, encoding='utf-8')))[key] is None)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
StopIteration

**Comment by jprouty** [comment]
Hi Brian,

Thanks for posting and glad you found the tool. Apologies that you're running into trouble.

Do you mind taking a look at your downloaded items report? It should be in whatever directory you ran the program from, AMZN Reports/some name Items from some date to some date.csv

Something isn't as expected with this report. If possible, would you mind replying with the first two lines of yours? Please feel free to obfuscate any personal information. Here's an example from my items report from a recent run:

```
Order Date,Order ID,Title,Category,ASIN/ISBN,UNSPSC Code,Website,Release Date,Condition,Seller,Seller Credentials,List Price Per Unit,Purchase Price Per Unit,Quantity,Payment Instrument Type,Purchase Order Number,PO Line Number,Ordering Customer Email,Shipment Date,Shipping Address Name,Shipping Address Street 1,Shipping Address Street 2,Shipping Address City,Shipping Address State,Shipping Address Zip,Order Status,Carrier Name & Tracking Number,Item Subtotal,Item Subtotal Tax,Item Total,Tax Exemption Applied,Tax Exemption Type,Exemption Opt-Out,Buyer Name,Currency,Group Name
06/05/19,114-5554492-3XXXXX5,"Stainless Steel Wall Mount Ceiling Mount Pipe Supports, Adjustable Pipe Bracket Clamp Pipe Strap for Dia 25mm (3/4-inch) Pipe Tube, Set of 2",Tools & Home Improvement,"B07K2QW2B1","30180000",Amazon.com,,new,NOVSINO,,$0.00,$15.35,1,"Visa - XXXX",,,my.email@gmail.com,06/06/19,Jeff Prouty,My address,,City, STATE,ZIP-CODE,Shipped,UPS(tracking number),$15.35,$1.55,$16.90,,,,Jeff Prouty,USD,
```

Cheers,
Jeff

**Comment by briansea** [comment]
Hi Jeff,

I just went and tried both of my amazon accounts again, and while both had this issue before, there are no problems now.  Sorry for the bother, and thank you very much for the help!

**Comment by jprouty** [comment]
It's a miracle! Thanks for the update and glad you're up and running :)
