### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by bjersky** [jprouty/mint-amazon-tagger#55]
Hi - I've been searching for a way to categorize Amazon purchases in Mint for quite some time and came across this option! How do I install this though? I don't know how to code, though I know a few small basics. Do I install it directly into Mint somehow?? And does this have access to our bank accounts and relevant data? Thanks

**Comment by dgraber95** [comment]
First, you'll need to install [Python](https://www.python.org/downloads/release/python-376/) 
Then, follow the instructions [here](https://pip.pypa.io/en/stable/installing/) to install Pip. Download get-pip.py, then run it with the given command. 
After that, just follow the instructions provided in the project ReadMe

- pip3 install mint-amazon-tagger
- mint-amazon-tagger

You'll probably need to add Python to your system Path. Pretty easy, just Google it for more info. 

This doesn't really integrate directly with Mint or Amazon, and has no access to bank accounts or anything. All it's doing is essentially automating the process of downloading all your purchase records from Amazon, then cross checking that with transactions in Mint. If price + date match up, the transaction is assigned details from the matching Amazon order from your order history. It's very nifty!

**Comment by jprouty** [comment]
@bjersky I just put in some serious hours this weekend to [hopefully] make your life easier. I've put together a GUI version that is much more user friendly. It's fresh of the press, so it might have so rough edges. Check out this project's main readme for links. I'm adding the mac os version next.

@dgraber95 is also correct, and that command will open the new GUI version. mint-amazon-tagger-cli will now give you the old CLI version.

Please try it out and let me know if you run into trouble!
- Jeff
