### ISSUE TITLE
Promotions are handled incorrectly

### ISSUE THREAD

**Issue by dgraber95** [jprouty/mint-amazon-tagger#56]
First off, this is a fantastic tool, so thank you for that! 

I'm seeing a (minor) problem where any coupons or discounts on Amazon orders are showing up as additional charges under the Mint split. 
See attached image. 
![image](https://user-images.githubusercontent.com/21182140/73131436-8e37f200-3fd0-11ea-843a-d9f6a8902767.png)

I purchased two items, with a combined promotion and coupon savings of $20.99. This shows up as a charge in Mint. If I go into the Split window in Mint, it tells me that my total needs to be my current value - 2x promotional value. See attached. 
![image](https://user-images.githubusercontent.com/21182140/73131472-056d8600-3fd1-11ea-83c5-b76e48e235c1.png)

I think the problem is that all promotional values should be negative charges (meaning they'd be money "coming in"). If I change that $20.99 to -$20.99, the error from Mint goes away.

**Comment by jprouty** [comment]
@dgraber95 Thanks for the report! Oddly enough, my personal mint shows this behavior as well, but back in dec 15, the tagger was properly inverting credits, and the splits correctly added up. I wonder if the mint team has some bad code live right now...

I'll work on a fix.

**Comment by jprouty** [comment]
And thanks for the general compliments; glad you're enjoying the tool! Any feedback/feature requests are welcome.

**Comment by jprouty** [comment]
Thanks again for the report! I've made an appropriate fix that will roll out today!
