### ISSUE TITLE
Allow CLI arguments to GUI

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#57]
Would be nice to populate those with the values passed. Am I missing something?

**Comment by cwmoriarty** [comment]
Just noticed the "-cli" version, but it'd still be good to populate from cli args!

**Comment by jprouty** [comment]
You're correct. I'll add support for cli args to the gui version 😛  I figured the average gui user would just click their options, but we clearly have some power users in the house. haha

**Comment by jprouty** [comment]
I've fixed this and it will be coming out in the next release.
