### ISSUE TITLE
don't add "Promotions" as separate items 

### ISSUE THREAD

**Issue by nitroamos** [jprouty/mint-amazon-tagger#6]
Hi, I'm giving your tool a shot... and it looks great! one thing I noticed from the dry run was that it was listing "Amazon.com: Promotion(s)" as separate transactions. I don't know what they're referring to specifically (Subscribe & Save?) -- but I don't care -- I don't want to have some special handling as a workaround however Amazon et al are playing with their pricing.

I'd prefer those items to be rolled into the item the promotion it was applied to.

**Comment by jprouty** [comment]
@nitroamos I appreciate the suggestion. Unfortunately, the Amazon order reports are not expressive enough to tell us which item the promo is applied to, just that a promo was applied to that order in general. So in that case, the only two options I can think of are:
(a) itemize as a separate line item (current implementation by default)
(b) split up the promo evenly and subtract from the individual items.
(c) do not itemize and lump the promo in with all the items/shipping/etc (implemented. try the `--no_itemize` flag).

Let me know if you have any other ideas/input.

**Comment by nitroamos** [comment]
Ah, a bit surprising that Amazon gives you so many details, but not this info.

Looking at my exports for 2017, almost all the promotions were 15% (from subscribe & save) so I think b would give me the correct value in most cases anyway.

Itemization is helpful for us wrt Amazon since we buy quite a bit across multiple Mint categories, that's why I came looking for your tool in the first place (i.e., a is preferred over c).

Another idea would be to just add all the promotions to a single line, but since Mint makes it easy to aggregate, I wouldn't chose it.

**Comment by jprouty** [comment]
I'm not sure I follow your last idea. Add all the promotions across orders? Or do you mean something else?

WRT how mint works, this tool in itemize mode basically creates a "split" as you can do in the Mint web interface. How this works roughly is: mint charge == sum(all items including tax) - order promo amount + order shipping.

**Comment by jprouty** [comment]
@nitroamos I had a few ideas as I was working on a rewrite. What do you think about the follow?

`--concise_itemize` a new flag. When present:
- do not itemize promotion (in the case of orders with 1 item, attribute all the promo to that item; in the case of orders w/ multiple items, spread it evenly between the items and keep the items itemized).
- do not itemize free 1-day shipping: (a shipping amount of X and a promo amount of -X)
- shipping will continue to be itemized if you paid for it
- itemizes are still split out on separate lines

**Comment by nitroamos** [comment]
That sounds good to me!

I hadn't really been thinking about shipping (because I have Amazon Prime and pick very few items with direct shipping costs) but I like your 2nd bullet point. A lot of vendors seem to play games with shipping costs -- e.g., give items a low price but then shipping is expensive, vs free shipping on a more expensive item, etc. My sense is that the most important number is just the total price (=price+shipping+taxes-promotions) because that aligns with how I want to use itemization in Mint and it's the number I'd want to compare apples-to-apples across various stores (including brick-n-mortar).

**Comment by jprouty** [comment]
Alright, I've changed the default behavior to be a bit more wise. By default:
- Free shipping is not itemized
- If there's only one item, don't itemize out shipping or promos (summarize it into one final line item)

To get the old behavior, use `--verbose_itemize`

Let me know if this is feeling better! Also, feel free to `--retag` or `--prompt_retag` to update the previous runs. or even `--retag --dry_run` to see how many changes would occur.
