### ISSUE TITLE
Not Categorizing

### ISSUE THREAD

**Issue by indygreg2** [jprouty/mint-amazon-tagger#61]
This is a GREAT app.  i am using the UI on windows and find two issues.  

 - it leaves everything categorized as shopping.  it clearly connects and updates the transactions so that the comments have the purchase details and orders are split but every category remains shopping.  
 - if i try to run from downloaded files it just hangs on the parsing step.  it will run if i let it log on to amazon.

**Comment by jprouty** [comment]
Thanks for the reports! I'll take a closer look, hopefully this coming week. Stay tuned!

**Comment by jprouty** [comment]
I fixed the 2nd issue (not yet released), and am in the process of fixing the first/primary issue (categories). It appears that Amazon decided to recategorize EVERYTHING recently. Haha. The upshot is that the new categories appear to be way more detailed!

**Comment by jprouty** [comment]
I have a new system that seems to be working much better now :) A release is shortly forthcoming.
