### ISSUE TITLE
GUI hangs indefinitely

### ISSUE THREAD

**Issue by glassdimly** [jprouty/mint-amazon-tagger#62]
Filing this bug for others.

Steps taken:
1. Install new gui on Mac
2. Run installed program
3. Experience GUI hanging

Fix
1. Upgrade `mint-amazon-tagger` with `pip3 install --upgrade mint-amazon-tagger`
2. Run `mint-amazon-tagger` from cli
3. See new interface working

**Comment by jprouty** [comment]
@glassdimly I see you closed the issue; did the console output help determine the issue? I do have a few bug fixes coming out shortly; there's a known issue with the amazon csv gui code (That will be fixed shortly)
