### ISSUE TITLE
fbs license violation

### ISSUE THREAD

**Issue by mherrmann** [jprouty/mint-amazon-tagger#63]
Hi,

author of [fbs](https://github.com/mherrmann/fbs) here. I'm happy you seem to be finding it useful!

fbs is licensed under the GPL. This means that code that uses it must also be GPL-licensed. Your project violates this. (It is not allowed to license under MIT.) I'd ask that you please license your code under the GPL instead.

Thanks,
Michael

**Comment by jprouty** [comment]
Thanks Michael, now on GPL.

**Comment by mherrmann** [comment]
Thanks!
