### ISSUE TITLE
error in refund array

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#66]
```
File "/usr/local/lib/python3.8/site-packages/mintamazontagger/cli.py", line 156, in log_amazon_stats
    first_refund_date = min(
ValueError: min() arg is an empty sequence

```

**Comment by jprouty** [comment]
Hi @cwmoriarty, Is this issue still happening for you? Can you provide any additional details of the steps to reproduce it?

Thanks!

**Comment by jprouty** [comment]
Closing this out as unable to reproduce. Thanks for the report (please reopen if this is still occurring and you have more information).
