### ISSUE TITLE
Can't download EXE file, Windows Defender identifies Trojan:Win32/Fuerboos.E!cl

### ISSUE THREAD

**Issue by OregonPinkRose** [jprouty/mint-amazon-tagger#71]
Windows Defender stops the download of the MintAmazonTagger.exe file. It finds Trojan:Win32/Fuerboos.E!cl Not sure why. Please look into this.

**Comment by jprouty** [comment]
Thanks for raising this! It looks like [this is happening](https://stackoverflow.com/questions/43777106/program-made-with-pyinstaller-now-seen-as-a-trojan-horse-by-avg). I had been signing windows binaries with my keys, but I lost my private key when moving machines (doh!). I'll update this thread once I've signed again, as well as trying the aforementioned fix in the link.

**Comment by jprouty** [comment]
@OregonPinkRose you should be all set. Please [try downloading again](https://github.com/jprouty/mint-amazon-tagger/releases/tag/1.33) from the 1.33 release. I have updated the file with a signed version and also using the technique I posted above. Windows defender may still give you a warning that this is a "rarely downloaded file" and also make you click through a pop up to get it running. Please reopen/report back if that's not working!

Cheers,
Jeff
