### ISSUE TITLE
Support mintapi's mfa-token option

### ISSUE THREAD

**Issue by felciano** [jprouty/mint-amazon-tagger#72]
It would be nice if `mint-amazon-tagger` could use the same authentication options for mint as are available in `mintapi`. In particular, using `--mfa-method "soft-token"` and `--mfa-token` would allow for token-based 2FA on systems that can generate the tokens in software.

**Comment by felciano** [comment]
I'm actually not clear on whether this is supported or not. There appears to be [code that processes](https://github.com/jprouty/mint-amazon-tagger/blob/76001c0705b1e2b498c86413df73f16859053c9b/mintamazontagger/api.py#L345) the soft tokens, but no way to pass them in from the command line.

**Comment by jprouty** [comment]
It should prompt for your token at the console you launched the cli from. `mfa_input_callback` should be None from mint amazon tagger side, which will cause `input` to be used.

I'm actually unfamiliar, what is the soft token option? Like an OTP device?

**Comment by felciano** [comment]
I'm not sure if "soft token" is a common term or not, but this `mintapi` parameter lets you pass in an identifier for the 2FA configuration code (the "soft token") for a given account, and then internally uses `oath` (see https://www.nongnu.org/oath-toolkit/) to generate the 6-digit code. The configuration code is the alphabetical version of the QR code you scanned when defining the OTP in Google Authenticator, 1Password or whatever your password manager of choice is. This should presumably be kept secure, but if you are comfortable storing your password in Keychain and then retrieving it on the commandline to feed into `mintapi` or `mint-amazon-tagger`, then presumably you could do the same for your "soft token"

**Comment by felciano** [comment]
Picking this up again @jprouty: when trying to run from the `cli` with a soft token, the app fails because it can't find the `oathtool` library refenced at https://github.com/jprouty/mint-amazon-tagger/blob/3642c33e7d04751ff5fdccbd45285883022ce1d1/mintamazontagger/mintclient.py#L417. Pretty sure this is just an omission from your `setup.py` file
