### ISSUE TITLE
If two factor auth is enabled on Mint, script hangs

### ISSUE THREAD

**Issue by noahsw** [jprouty/mint-amazon-tagger#8]
First off -- this tool could save me hours!! Very excited to get it into use.

While playing with it, I noticed the script hung at login. I switched to the Chrome window and saw that Mint was waiting for my MFA input. This is probably easy to detect so you could alert the user that they need to switch over and take care of it before the script can resume.

Great work!

**Comment by jprouty** [comment]
This is more of a feature for https://github.com/mrooney/mintapi. The API doesn't give the script/app a way to know the current progress of the auth request.
