### ISSUE TITLE
MintAPI 

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#81]
MintAPI has a few different parameters that would be good to pass as arguments, namely `use_chromedriver_on_path` so we can use a native (eg ARM64) chromedriver, but also MFA and others. Have you considered adding additional arguments?

**Comment by jprouty** [comment]
Hi @cwmoriarty, this tool no longer uses MintAPI (I wrote a more robust login flow, created a cleaner api for this tool, and removed some significant size dependencies, making the releases much smaller).

Can you describe the feature request(s) you have specifically so I can accommodate? Thanks!

**Comment by cwmoriarty** [comment]
Ah! Good to know. I just want to run this on ARM64/Raspberry PI. I think I ran into some issues before the MintAPI breakup?

**Comment by jprouty** [comment]
Gotcha, please reopen if you run into issues. The chromedriver portion is very similar to mintapi (I refactored it / added the path overrides to MintAPI). So there very well could still be a feature request here to get you running. Thanks
