### ISSUE TITLE
Add MFA flow to Amazon login (useful/critical for --headless mode)

### ISSUE THREAD

**Issue by cwmoriarty** [jprouty/mint-amazon-tagger#82]
Amazon MFA (2SV) in `--headless` mode doesn't work. 

If I didn't have a 👶 due in the next few days, I'd write up a PR for a "semi-headless" mode which would prompt for an OTP. Checking "Don't require OTP on this browser" with chromedriver would be cool too, but keeping that persistent is probably challenging.

**Comment by jprouty** [comment]
There is no MFA logic for the amazon login flow at the moment. If you have a MFA challenge, you need to complete it yourself in the browser (which as you point out won't work well if you're running --headless).

I'll rename the FR. Thanks for the report and congrats on the new baby!
