### ISSUE TITLE
Error: Internal error while creating updateS: no Module named "oathtool"

### ISSUE THREAD

**Issue by ron23** [jprouty/mint-amazon-tagger#85]
I think it has something to do with Mint being setup with 2FA using authenticator app. I can't go past the login.

**Comment by jprouty** [comment]
Thanks @ron23. This is my mistake when I was pruning some python dependencies. Should be fixed in the next release.

**Comment by jprouty** [comment]
This should be fixed in the new 1.39 release. Please let me know if you still have trouble!
