### ISSUE TITLE
Amazon Order History Report Stuck

### ISSUE THREAD

**Issue by ovitch** [jprouty/mint-amazon-tagger#87]
Hi. I tried to use the software like I do every month and I can't get Amazon to process the report. They get stuck on Processing (0%). Am I the only one to have that issue? Hard to tag is the raw material is not available...

**Comment by greeen-tea** [comment]
Hi. I have the exact same issue. Even when creating reports manually. It is stuck at "0% processing". It seems like an error on Amazon's end.

**Comment by jprouty** [comment]
Thank you both for the report! I am seeing the same thing (unfortunately).

Please _report_ back if your report completes! Note: If you rerun the tagger on the same day (or select the same range of dates), it will reuse the already processed report instead of requesting another one. However, it will require a few rounds, as it will block on items, then orders, then refunds.

**Comment by ovitch** [comment]
Glad to know I am sane. I called amazon bu they weren't helpful. I think we need to get a technical ticket somewhere but unsure where to ask. Any ideas?

**Comment by ovitch** [comment]
https://www.amazonforum.com/s/question/0D56Q00008LqV79SAF/order-history-reports-csv-download-

**Comment by craiglathrop218** [comment]
You have to wait a day or two for the report to process. I manually triggered the reports, then came back two days later and they were ready. Oddly, I did one test that was only 5 days and that one is still running.

**Comment by ovitch** [comment]
I did tried for 3 weeks now. Eventually they all failed and no data was released. It seems the problem happens a lot but I gave up calling amazon. Ask 5 times to notify the technical team and they always fail to send the email with the ticket number...

**Comment by jprouty** [comment]
I've had some intermittent success as well. Keep trying @ovitch (maybe try smaller date ranges?). However, there clearly is an issue/bug on Amazon's side; I imagine this will clear up sometime in January on "it's own". Hang in there!

**Comment by ovitch** [comment]
@jprouty I tried it again many times, small chuncks, big chunks. But today by some kind of miracle it finally worked. Did it in 2 sec for 2021 (all year). Hopefully this works with the tagger!

**Comment by jprouty** [comment]
@ovitch I have noticed the same thing! Please give the tagger another go and reopen this issue if it happens again or file a new one if you run into a new problem. Thanks for the early initial alert!
