### ISSUE TITLE
Errors when using manual import

### ISSUE THREAD

**Issue by craiglathrop218** [jprouty/mint-amazon-tagger#88]
As Amazon reports now take over 48 hours to generate, I'm using the manual report import method. I tried running this on a Mac, and a Windows machine, but I get errors (different errors).

Windows: `Error: Internal error while creating updates: input(): lost sys.stdin`
Mac: `Error: Internal error while creating updates: EOF while reading a line`

I tried opening the files up and re-saving them, also ensuring that the last column "group" which was empty has a value. I have no returns in this period so that file is just an empty header. I tried both with the file selected and without, same issue. 

Also, just a note, but every time I open I get a message about a new version being available despite being on the latest.

**Comment by jprouty** [comment]
Thanks for the report; I'm able to replicate your issue and can take care of the new version issue at the same time. Stay tuned.

**Comment by jprouty** [comment]
This should be fixed in the new 1.39 release. Please let me know if you still have trouble!
