### ISSUE TITLE
How do you detect if an item has already been manually tagged?

### ISSUE THREAD

**Issue by noahsw** [jprouty/mint-amazon-tagger#9]
I saw this in my dry run:
```
Current: 	11/12/17 	 $39.77 	 Pets 	 Amazon

1) Proposed: 	11/12/17 	 $46.14 	 Shopping 	 Amazon.com: ROYAL CANIN FELINE HEALTH NUTRITION Indoor Adult dry cat food, 15-Pound
2) Proposed: 	11/12/17 	 -$6.37 	 Shopping 	 Amazon.com: Promotion(s)
```

Notice I had already tagged the category to Pets but it looks like your script wants to change it back to shopping (because the Amazon category is "Misc" unfortunately)

**Comment by jprouty** [comment]
@noahsw Thanks for all the great suggestions.

The tool uses the two "prefix" CLI args for both writing new tags as well as determining if something has been tagged already.

Take a look at [all the args and help strings here](https://github.com/jprouty/mint-amazon-tagger/blob/master/tagger.py#L602) or with ` --help`

I'm not sure if there's an easy way to exclude Mint transactions from being tagged. Maybe allow for users to pass in an exclusion regex?

**Comment by jprouty** [comment]
Give `--mint_input_categories_filter=Shopping` a shot! Just committed

**Comment by noahsw** [comment]
Works great! Thx @jprouty !
