### ISSUE TITLE
Support CA Marketplace

### ISSUE THREAD

**Issue by zsolteszku** [jprouty/mint-amazon-tagger#90]
It would be great if this tool would support amazon.ca and not just amazon.com

**Comment by jprouty** [comment]
Hi @zsolteszku. I do not have a CA account. Would you mind describing the issues you run into using the tagger tool as it is today? ie, what portion of the workflow do you get stuck on?

Also, you ought to be able to manually download the report files for the dates of interest and use those with the tagger tool to update mint. Let me know if this flow is giving you issues too.

Thanks!

**Comment by zsolteszku** [comment]
Hi @jprouty, Thanks a lot for your help.

To be honest I got stuck at the beginning of the manual workflow. I was not able to export the payment history as that page only exists for US. Is there any other way that you know of that I could extract those information from Amazon? I found a [google chrome extension](https://chrome.google.com/webstore/detail/amazon-order-history-repo/mgkilgclilajckgnedgjgnfdokkgnibi?hl=en) that does something similar but it does not look like to contain all information that this tool would need. What is the minimum set of information that the tool requires to run the tagging?

Thanks!

**Comment by jprouty** [comment]
I was able to log in with my US Amazon account to Amazon.ca. I also navigated to the matching order history report page, and that informed me I didn't have any orders. However, it seemed like it might work.

Do you mind trying this page to get your data?
https://www.amazon.ca/gp/your-account/order-history

**Comment by jprouty** [comment]
Please reopen the issue if that link does not work for you. Thanks!

**Comment by s0j0urn** [comment]
@jprouty This doesn't work for amazon.ca. Issue is same as described. Amazon.ca doesn't have an order history report page. There exists an extension as mentioned above which can fetch the data in a csv format but not sure if that will work with this tool. Please take a look

**Comment by jprouty** [comment]
Unfortunately the chrome extensions will not put the data in the right format (or without undue effort to rework the tool). In addition there are quite a few quirks in their business logic that have been worked around based on how the b2b reports work. The quirks from the standard invoices are different and again would require a large effort to understand.

Do you mind reporting what http status code you get when visiting this url, after having logged in successfully? https://www.amazon.ca/gp/your-account/order-history

Thanks
