### ISSUE TITLE
Stale element reference error when updating Mint transactions

### ISSUE THREAD

**Issue by konriar** [jprouty/mint-amazon-tagger#91]
"stale element reference": "element is not attached to the page document" 

Chrome 97

**Comment by jprouty** [comment]
@konriar Can you describe the last page that was visible during this session before you received this error? Thanks

**Comment by konriar** [comment]
It was the screen on Mint after successful login, while it synced accounts. It seemed to get stuck at that screen. I tried a few more times with "Sync First?" checked in the tool. After a few tries it matched the Amazon and Mint data well, and the tagger took a few minutes to run. 

The tagger ended with an error: "Internal error while sending updates: 'MintCLient object has no attribute 'close'.

However Mint appears to be updated with the matched order data, so it ran successfully.

**Comment by kwylie** [comment]
I think I have the same issue.  "Error: Internal error while creating updates: Message: stale element reference: element is not attached to the page document (Session info: chrome=97.0.4692.71)".

Login is successful, updates fail.

**Comment by kwylie** [comment]
@jprouty: any ideas here?  I haven't had a successful run in months due to this error.

- mint-amazon-tagger==1.41
- Chrome (Mac OS) Version 98.0.4758.80 (Official Build) (arm64)

**Comment by jprouty** [comment]
@kwylie, sorry for the trouble (and the delay to address this issue). I'm going to need a bit of help finding the issue, as I'm unable to replicated it myself.

I have made a new release, 1.42 with some more detailed logging around both the amazon and mint login flows as well as one possible fix for a section that might cause a stale reference error. Do you mind trying this new version and reporting back what you find?

If it doesn't work, can you describe in detail what part of the process or page/url that the stale reference error occurs at? Also, if you could provide the corresponding log file, that would be helpful (can be found at `/Users/$USER/MintAmazonTagger/Tagger Logs/DATE_OF_RUN.log`) - feel free to redact any sensitive paths/content. You're also welcome to email it to me at jeff.prouty@gmail.com for privacy sake (versus posting here).

Thanks!
Jeff

**Comment by talon256** [comment]
I updated to 1.42 just now and ran it three times. Different errors each time. Posting here b/c of #2.
1. Got the error saying Chrome 97 is no longer supported, updated Chrome.
2. This error (attaching .log). Just re-ran without changing anything...
3. Different error: "Error: Internal error while creating updates: Message: invalid argument: user data directory is already in use,please specify a unique value for --user-data-dir argument,or don't use --user-data-dir" (created a new issue thread for this one w/ detail).

[2022-02-07_10-16-00.log](https://github.com/jprouty/mint-amazon-tagger/files/8017499/2022-02-07_10-16-00.log)

**Comment by kwylie** [comment]
I had no issues on 1.42 today!  Hopefully the extra logging helps with future issues.  I appreciate you taking a look!

**Comment by jprouty** [comment]
Thanks for the logs @talon256. 1.43 will include a possible fix; I have a feeling your page was updating just slow enough that it was causing the script to get hung up. Please reopen if you see if happen again on 1.43 or later!

**Comment by jprouty** [comment]
My pleasure and glad to hear you're enjoying the tool. Thank you for all of the useful feedback (helpful to me and others)!
