### ISSUE TITLE
'MintClient' object has no attribute 'close' at end of run

### ISSUE THREAD

**Issue by felciano** [jprouty/mint-amazon-tagger#94]
Just re-ran `mint-amazon-tagger` for the first time in about 3 months, and find that it is reliably failing on the last step. As far as I can tell, transactions are being updated correctly, but there appears to be an error during the final clean-up. The error occurs and is visible on the command-line as well as in the GUI.
```
Creating a new webdriver
Getting Mint categories.
Get all Mint transactions since 2021-04-07.
Internal error while sending updates: 'MintClient' object has no attribute 'close'
Traceback (most recent call last):
  File "/Users/<username>/.cache/pypoetry/virtualenvs/tagmint-1tgIL90G-py3.9/lib/python3.9/site-packages/mintamazontagger/main.py", line 623, in send_updates
    self.do_send_updates(updates, args)
  File "/Users/<username>/.cache/pypoetry/virtualenvs/tagmint-1tgIL90G-py3.9/lib/python3.9/site-packages/mintamazontagger/main.py", line 689, in do_send_updates
    self.mint_client.close()
AttributeError: 'MintClient' object has no attribute 'close'
Internal error while sending updates: 'MintClient' object has no attribute 'close'
```

**Comment by jprouty** [comment]
Hi @felciano! The updates were pushed to Mint. This error was [first reported here](https://github.com/jprouty/mint-amazon-tagger/issues/89) and is fixed at HEAD, but I haven't cut new binary releases just yet. I'll do that now. Thanks for checking in.

**Comment by felciano** [comment]
Ah sorry my bad--should've found that on my own--thx

**Comment by jprouty** [comment]
My apologies! I was just being laze. The 1.41 release is all there and should be good to go. Thanks
