### ISSUE TITLE
Feature Request: "Report Error" functionality

### ISSUE THREAD

**Issue by talon256** [jprouty/mint-amazon-tagger#96]
While helping report bugs and errors, it would be convenient to be able to select and copy the text in the error message. 
Even cooler to just have a button that says 'copy error text'.
Coolest to have a button that says 'report error' that redirects to the issues page to either add to an existing conversation or report a new error.

**Comment by jprouty** [comment]
Great point @talon256. The copy / paste at a minimum seems helpful.

Note: the tool does save logs to your user's home directory (os dependent), e.g. for macOS: `/Users/$USER/MintAmazonTagger/Tagger Logs/DATE_OF_RUN.log`). This file would be the most helpful when filing a bug report; thanks!

**Comment by jprouty** [comment]
Thanks for the FR @talon256. The text is now copyable in 1.43. I'll leave this open as a future FR to make reporting even easier.

**Comment by talon256** [comment]
> have a button that says 'report error' that redirects to the issues page to either add to an existing conversation or report a new error.

I realized today that something as simple as a 'Go to GitHub' option on the menu bar drop down (on Mac) or file menu (on PC) would be very nice for 'bookmarking' this forum. That's probably much easier to implement than the 'report error' button, but basically just as helpful.

**Comment by jprouty** [comment]
I've added a report button to the UI as well! Unfortunately github's url API isn't rich enough to be extremely useful, but good enough.
