### ISSUE TITLE
Internal error while creating updates: invalid argument: user data directory is already in use

### ISSUE THREAD

**Issue by talon256** [jprouty/mint-amazon-tagger#97]
I updated to 1.42 just now and ran it three times. Different errors each time. Posting here b/c of #2.
1. Got the error saying Chrome 97 is no longer supported, updated Chrome.
2. This error (attaching .log). Just re-ran without changing anything...
3. Different error: "Error: Internal error while creating updates: Message: invalid argument: user data directory is already in use,please specify a unique value for --user-data-dir argument,or don't use --user-data-dir"

The 3rd error I've received several times before updating to 1.42, and just waited to see if it would fix itself in the 1.42 release before reporting. I only receive it after having received a different error previously and attempting to re-run. 

I've resolved this error by simply quitting and reopening MintAmazonTagger, which allowed me to continue. 

I have had a successful run after receiving this error without quitting, but I had waited 30+ minutes after the error before running again. I've tried simply re-running, which doesn't work. 

Log: [2022-02-07_10-16-00.log](https://github.com/jprouty/mint-amazon-tagger/files/8017576/2022-02-07_10-16-00.log)
Successful Log (after quit and reopen) FWIW: 
[2022-02-07_10-52-53.log](https://github.com/jprouty/mint-amazon-tagger/files/8017581/2022-02-07_10-52-53.log)

**Comment by jprouty** [comment]
Thanks for the post @talon256. This should be fixed in 1.43 (going out shortly).
