### ISSUE TITLE
No data found in Amazon reports

### ISSUE THREAD

**Issue by ChopSu3y** [jprouty/mint-amazon-tagger#98]
HI all, when running the application. I see that there is no data in the reports that the application downloads. I changed the time ranges as well, but still no luck. This is an error on amazon's side. I was wondering if anyone else has seen the same? Thanks!

**Comment by talon256** [comment]
Yes, l got the same error as well today.


Sent from my Apple Watch

**Comment by cwmoriarty** [comment]
Same.

**Comment by jprouty** [comment]
Oh wow, that's not very helpful :( On the plus side, it's way faster to process the report now :-P

**Comment by jprouty** [comment]
Interestingly, I tried `12/31/20 - 01/01/22` and that did not complete, ending with a "Failed" status, and taking about a minute before (I assume) timing out.

**Comment by jprouty** [comment]
This appears to be resolved as of today; please reopen if this occurs again. Thanks @ChopSu3y for the original report/heads up.
