### ISSUE TITLE
Says can not login into Mint

### ISSUE THREAD

**Issue by SmoothCamera** [jprouty/mint-amazon-tagger#99]
If I do it manually or automatically I can not get the program to think it is logged into mint. on MacBook Pro. have tried two now. abbe cuz I have multiple accounts?

**Comment by alex-tomin** [comment]
Same here.. Did Mint make some changes?

**Comment by jprouty** [comment]
Thank you both for the report and the screen shot. I'm taking a look now.

**Comment by jprouty** [comment]
Good news; I was able to run the tagger without a problem. I think you both may be running old versions and it's not entirely your fault :) I haven't released a prebuilt version for windows for a while (And it looks like @alex-tomin was on windows based on the screen shot).

Can I bother either of you to attempt again, this time using HEAD (if from source), or using PyPI or [rebuilt binaries with a version of 1.43](https://github.com/jprouty/mint-amazon-tagger/releases/tag/1.43).

Thanks!
Jeff

**Comment by alex-tomin** [comment]
Oh... you are right, I forgot to mention the version.  Will check tonight and let you know. 

Thanks for prompt look!

**Comment by aleto-ms** [comment]
@jprouty I can confirm le latest works! Thanks a lot for uploading windows version and for the amazing tool 🎉

**Comment by SmoothCamera** [comment]
I am on mac. but honestly barley figured out how to run it from terminal.
or. no idea how to do this

 (his time using HEAD (if from source), or using PyPI or rebuilt binaries
with a version of 1.43
<https://github.com/jprouty/mint-amazon-tagger/releases/tag/1.43>.).

looking forward to the update tho.

**Comment by jprouty** [comment]
Thanks @aleto-ms and @alex-tomin for confirming it works now. @SmoothCamera, please reopen/reply if the tool continues to give you difficulty. Screen shots of any error messages/etc would be appreciated.
